### ISSUE TITLE
Figure 3.4 = demographic transition theory

### ISSUE THREAD

**Issue by jgvanantwerp** [MatthewHeun/MCBook2021#101]
Jeremy to find data. US data OR another country with a "clean" look.
Matt(?) make two plots, top = birthrate and death rate. bottom = population.
Either eliminate population pyramid OR make is a separate graph.

**Comment by MatthewHeun** [comment]
Have Anjana look for read data from U.S. Generated and age specific breakdowns back to 1800. Also maybe breakdowns by race.

**Comment by jgvanantwerp** [comment]
Section 3.2.3 -- check that "stage" (diagram) OR "phase" (text) is used consistently in both text AND figure.

**Comment by MatthewHeun** [comment]
A figure is now in the chapter. So I'm taking my name off this issue.

**Comment by MatthewHeun** [comment]
MKH to add population pyramids to Figure 3.4. Reassigned to MKH.
