### ISSUE TITLE
Strong sustainability definition and consistent use

### ISSUE THREAD

**Issue by jgvanantwerp** [MatthewHeun/MCBook2021#104]
In section 5.1.1, Daly's second law is that "Nonrenewable resources, such as minerals and fossil fuels, must be used no
faster than renewable substitutes for them can be put into place."

However, later in the section, it says "By the “strong sustainability” criterion, any extraction of construction minerals, ores and industrial minerals, and fossil energy carriers is unsustainable, because these materials do not regenerate on human timescales."

Still later, in Section 5.3 it says "By the strong sustainability criterion of consuming resources at a rate beneath their regeneration rate, none of the fossil fuels shown in Figure 5.5 are being consumed at a sustainable rate."

So, two questions:
1. What does "no faster than renewable substitutes can be put into place mean?"
2. Can some use of fossil fuels be sustainable if we are replacing them with (sustainable) biofuels?

In particular, let's consider an example with Daly's rule #2. Suppose we're using petroleum at a rate of 50k bbl/day. What would it mean for the rate at which a renewable substitute to be "put into place?" It seems to me that Daly means something like we have a weak-sustainability-timeframe to get to the point of having 50k bbl/day of biofuels.

**Comment by MatthewHeun** [comment]
The definitional of weak and strong sustainability have been clarified in Ch5. I'm closing this issue now. But we should still double-check that we are using the terms correctly elsewhere.
