### ISSUE TITLE
Caption for figure 5.7 and 4.2 = units inconsistent

### ISSUE THREAD

**Issue by jgvanantwerp** [MatthewHeun/MCBook2021#105]
Figure 4.2 is in T$ and Figure 5.7 is in $.
I'm guessing that T is thousand and that seems like it ought to be the correct unit. 
(that is, 4 MJ of energy creates a thousand dollars of 2017 GDP, not one dollar of GDP.)
which is correct?

**Comment by MatthewHeun** [comment]
Figure 4.2 is definitely in T$:

```
world_gdp_Nordhaus %>%
  dplyr::mutate(
    GDP_trillion_2017_intl_dollars = world_gdp_2017_intl_dollars / 1e12
  ) %>% 
```

Figure 5.7 is in MJ/dollar. Note that the `world_gdp_2017_intl_dollars` variable in the following code is in dollars, not T$.
```
  dplyr::mutate(
    energy_per_GDP_MJ_per_dollar = energy_TWh * 3600000000 / world_gdp_2017_intl_dollars  # 3600000000 MJ / TWh
  ) 
```

So the units ARE correct already. I'm closing this issue but *making no changes*.
