### ISSUE TITLE
Add G&A figure 5.1 to chapter 5 in the discussion of strong and weak sustainability

### ISSUE THREAD

**Issue by jgvanantwerp** [MatthewHeun/MCBook2021#106]

**Comment by MatthewHeun** [comment]
Or figure 1.5.

Amount extracted, amount available curve. Cost function.

**Comment by MatthewHeun** [comment]
Neither Figure 1.5 nor Figure 5.1 seems to be the right figure.

**Comment by MatthewHeun** [comment]
Fixed the discussion of Weak Sustainability. Also, we decided NOT to use G&A Figure 1.1.
