### ISSUE TITLE
Personal IPARC equation project

### ISSUE THREAD

**Issue by MatthewHeun** [MatthewHeun/MCBook2021#107]
Ask students to do their own personal IPARC equation. 

Impact = # of people in family * affluence of your family * resource intensity of the economy (probably not determined on a per-person basis, rather determined by the economy in which you live) * carbon intensity of resources (probably not determined on a per-person basis, rather determined by the economy in which you live)

**Comment by jgvanantwerp** [comment]
created project P1.5. MKH to review and close issue.

**Comment by MatthewHeun** [comment]
With a few minor edits, it looks good (great!) to me.
