### ISSUE TITLE
Add to chapter 5 a section on transitions

### ISSUE THREAD

**Issue by jgvanantwerp** [MatthewHeun/MCBook2021#109]
\section{patterns of resource use}
Contrast exponential growth with a logistic curve.
Some things will continue to grow.
Others have a logistic adoption. Early on, their growth might appear exponential. 
it's wise to know which model to base future predictions on.
Nonrenewable resources, like coal and oil have logistic use curves (fraction extracted).
Renewable resources, like fisheries and forestry, have an inverted parabola (G&A figure 1.1).
Others (?) might be exponential, say the number of humans or total computing power.

**Comment by MatthewHeun** [comment]
This has been accomplished, but focused on resource intensity. Ch6 is focused on carbon intensity of energy.
