### ISSUE TITLE
terminology chapter 7

### ISSUE THREAD

**Issue by jgvanantwerp** [MatthewHeun/MCBook2021#116]
Housing vs. household vs. dwelling vs. housing unit.

IEA uses "housing unit."
"household" would seem to refer to the group of people living together.

**Comment by MatthewHeun** [comment]
Definitions:

* household: a house and its occupants regarded as a unit: the whole household was asleep | [as modifier ] : household appliances | ten percent of households had a television.
* dwelling: a house, apartment, or other place of residence: the proposed dwelling is out of keeping with those nearby.
* housing: houses and apartments considered collectively: affordable housing | [as modifier ] : a housing development.
* housing unit: A housing unit is a single unit within a larger structure that can be used by an individual or household to eat, sleep, and live. The unit can be in any type of residence, such as a house, apartment, or mobile home, and may also be a single unit in a group of rooms. Essentially, a housing unit is deemed to be a separate living quarter where the occupants live and eat separately from other residents of the structure or building. They also have direct access from the building's exterior or through a common hallway.

Seems like the following should apply:
* household: people + sttructure
* housing unit: structure only
* dwelling: structure only
* housing: structures (both houses and apartments)

**Comment by MatthewHeun** [comment]
Scanned through the chapter and attempted to be more precise in the terminology.

**Comment by MatthewHeun** [comment]
We want definitions at the beginning of Ch7.

**Comment by MatthewHeun** [comment]
Added the definitions.
