### ISSUE TITLE
Caption/axes for figure 7.2

### ISSUE THREAD

**Issue by jgvanantwerp** [MatthewHeun/MCBook2021#117]
1. [y-axis] Is GJ the correct amount? It seems high.
2. [y-axis] "Average" -- does this mean the stacked bars are an average amount for a house of this size? Is so, why so much fuel oil? It's basically only used in the NE. Did you maybe grab regional data by mistake?

**Comment by MatthewHeun** [comment]
1. Data are from EIA Table CE2.1. Data in table are labelled as "Average site energy consumption1(million Btu per household using the fuel)". In R, I multiply million BTU by 1.05506 to obtain GJ. (See https://www.inchcalculator.com/convert/million-btu-to-gigajoule/ for the unit conversion.) I think this is correct.

**Comment by MatthewHeun** [comment]
Fixed by doing a better average of energy consumption.
