### ISSUE TITLE
"summer" and "winter"

### ISSUE THREAD

**Issue by jgvanantwerp** [MatthewHeun/MCBook2021#121]
vs. "when it's hot outside" and "when it's cold outside."
Would more generic language be preferable because it doesn't assume where the readers live?

**Comment by MatthewHeun** [comment]
I'm pretty sure I already addressed this issue, because I can't find "when it's hot outside" in Ch11. I also see the text where this phrase *was*, and it now says "summer" and "winter." 

So I'm closing this issue.
