### ISSUE TITLE
Verify that Figure 7.4 excludes biomass, coal, district heating, and solar thermal.

### ISSUE THREAD

**Issue by jgvanantwerp** [MatthewHeun/MCBook2021#128]
If it does, add a sentence stating that to the caption.

**Comment by MatthewHeun** [comment]
This is now Figure 7.5.

**Comment by MatthewHeun** [comment]
The Excel file ce2.1 has a footnote:

```
1Consumption and expenditures for biomass (wood), coal, district steam, and solar thermal are excluded. 
```

The note in the figure caption is correct. ("Biomass (wood), coal, district steam, and solar thermal are excluded. ") 

So this issue is verified. Now closing.
