### ISSUE TITLE
References or URLs

### ISSUE THREAD

**Issue by MatthewHeun** [MatthewHeun/MCBook2021#129]
We would do well to have a discussion about URL references and hyperlinks.

At the moment, we are inconsistent: some are references, some are URLs straight in the text.

**Comment by MatthewHeun** [comment]
URLs for See Also.
Links everywhere else.

**Comment by jgvanantwerp** [comment]
Compare chapter 8 and chapter 9. I'm thinking that perhaps some links in See Also would look/work better.
