### ISSUE TITLE
Summary tie back to IPARC for chapters 7, 8, 9.

### ISSUE THREAD

**Issue by jgvanantwerp** [MatthewHeun/MCBook2021#131]
Currently in chapter 10: "Therefore, consistent with earlier chapters, the drivers for land use are the terms of the IPARC equation, (P ), (A), and (R)."

MKH commented: "I like that a LOT.  Maybe we should spread that idea to Ch 7-9?"
I think i've already go this in chapter 9. 
"Thus, the global demand for food has two main drivers: population ($P$) is the primary
driver of demand and affluence ($A$) is the secondary driver."

**Comment by MatthewHeun** [comment]
I have added ties to IPARX for Ch7 and Ch8. I think that completes this issue, so I'm closing it now.
