### ISSUE TITLE
chapter 6 further reading

### ISSUE THREAD

**Issue by jgvanantwerp** [MatthewHeun/MCBook2021#136]
The word "Publisher" should be removed from the title of Edward Humes book "Garbology."
For some reason, this isn't showing up in my JabRef version of the bib file.

**Comment by MatthewHeun** [comment]
This reference was not showing up in the MCBook.bib file, because the Further Reading references are simply typed into the manuscript.

Regardless, I deleted the word "Publisher" from the manuscript.
