### ISSUE TITLE
Data for last mile figure

### ISSUE THREAD

**Issue by MatthewHeun** [MatthewHeun/MCBook2021#138]
We need data for the last mile pie graph.

**Comment by jgvanantwerp** [comment]
Use data from the existing figure. Create our own pie chart in R using those 4 percentages. I've changed source to be "Honeywell." in the caption.

**Comment by MatthewHeun** [comment]
Chart created. 

I referenced the Business Insider article and noted that it was accessed in 2018, when the figure we used was present. (The pie chart is no longer present in the article.)
