### ISSUE TITLE
Swap order of Ch11 and Ch12?

### ISSUE THREAD

**Issue by MatthewHeun** [MatthewHeun/MCBook2021#141]
Maybe having person action first is better. At the end of the personal action chapter, we can say that personal action is not enough. (the CO2 emissions curve is still going up, despite the individual actions of sooooo many people who care.) The sustainability challenges exist at the corporate level, too. So we need action on the corporate level.

Decide after feedback from Julie's class.

**Comment by MatthewHeun** [comment]
Currently, I'm thinking that *not* changing the order would be best. I.e., Ch11: Corporate Actions and Ch12: Individual actions. 

Reason: I like the ending of Ch12 being the ending of the book, namely the list of things individuals can do after reading the book.

If JVA agrees, he can close this issue.

**Comment by jgvanantwerp** [comment]
I do agree.
