### ISSUE TITLE
Definition of weak/strong sustainability

### ISSUE THREAD

**Issue by MatthewHeun** [MatthewHeun/MCBook2021#156]
Tania Sousa wrote:

I like this definition [Herman Daly] of environmental sustainability. How do we use the IPARC equation to evaluate sustainability? How does an Impact number tell you if you are or are not using renewables resources faster then they regenerate?Is there an intimate relationship between these criteria and the way planetary boundaries were obtained? In the IPARC equation sustainability is measured both in the "I" and the "R" . Can you make this clearer?

**Comment by MatthewHeun** [comment]
I take this comment to be another push to clarify the sustainability framework (weak, strong, etc.). Other similar issues are: #38, #62, #108, #122. 

I *think* we decided that we *didn't* like the Herman Daly definition and were planning to excise it from the book, because it is ambiguous and unhelpful. 

This comment needs much discussion.

**Comment by jgvanantwerp** [comment]
I **did** excise Daly from chapter 1. However, that doesn't prevent us from strengthening definitions of weak and strong sustainability in chapter 1. In fact, chapter 1 probably _does_ need a clear definition of sustainability (or an explanation of _why_ we're not giving a definition).

**Comment by MatthewHeun** [comment]
Gregor said:

p. 6 in environmental economics strong and weak sustainability are differently defined, and have to do with substitutability of types of 'capital'. I find the whole natural capital etc debate really misplaced because I don't think trying to force 'nature' into a 'capital' corsett and claiming it is commensurable with produced capital is a good analytical lens. There are also many unresolved problems in produced capital theory. So I am glad you're not referring to this natural capital definition here, but I think you should be aware of this discourse (very likely you are) and possible confusions arising from people who know it and read your book.  I attach a Dietz & Neumayer (2007) paper for some discussion.

I should skim Dietz and Neumayer to see if there is anything relevant for where we want to send the weak/strong discussion.

**Comment by MatthewHeun** [comment]
After an afternoon of work, I have reworked the strong and weak sustainability discussion in Ch1 and Ch5. So I'm closing this issue and several related issues.
