### ISSUE TITLE
Contamination intensity --> impact intensity of resources?

### ISSUE THREAD

**Issue by MatthewHeun** [MatthewHeun/MCBook2021#160]
Tania Sousa wrote:

I don't like "contamination intensity". I would prefer "impact intensity of resources". Contamination seems too narrow.

**Comment by MatthewHeun** [comment]
This comment has some merit, because the term (C) is really impact/resouce. 

Options:

* X = impact intensity of resources --> IPARC becomes IPARX (pronounced i-parks)
* Make no changes

This comment needs discussion, because a change will be rather drastic and far-reaching.

**Comment by jgvanantwerp** [comment]
Let's do it. That also frees up C to be consumption.

**Comment by MatthewHeun** [comment]
This has been accomplished to the best of our ability at this time. We need to look for places where a stray "C" remains and convert to "X".
