### ISSUE TITLE
chapter 2 intro -- Grawe

### ISSUE THREAD

**Issue by jgvanantwerp** [MatthewHeun/MCBook2021#165]
Here again, you are making assumptions about technological change that haven’t been true in the past.  200 years ago, Jevons was warning we would imminently run out of coal.  His argument was exactly yours.  And technological innovation in extraction made it wrong. I’m not saying that you shouldn’t call out the tension.  Just saying you can make your point without the same problems if you’ll tack on an if statement. “Why is continued exponential growth impossible—at least without offsetting growth in technology that increases the efficiency of resource user?”

**Comment by jgvanantwerp** [comment]
MKH to add a box or something to chapter 5 to address the idea that efficiency (that is, increasing technology) can save us (or at least, will lead to never-ending economic growth).
* diminishing returns
* efficiency leads *increasing* use (Sorrell, 5 propositions)
* Resources per GDP is mostly flat (see Figure 5.3), NOT going to zero.
* England *did* run out of coal, see Figure 5.10. (This point maybe isn't really relevant.)

**Comment by MatthewHeun** [comment]
It seemed that the best place to add this content was in the interactions section in Ch6. I added quite a bit of material in Section 6.6.3.

**Comment by MatthewHeun** [comment]
At JVA's suggestion, reopening to reduce the amount of detail on Sorrell. Too much vocabulary that is not discussed in the book itself. Probably too much for 1st and 2nd year students.

**Comment by MatthewHeun** [comment]
Moved Sorrell discussion to a project. Now re-closing this issue.
