### ISSUE TITLE
Move Indices section to Chapter 1?

### ISSUE THREAD

**Issue by MatthewHeun** [MatthewHeun/MCBook2021#167]
Tania Sousa wrote (about Section 2.4):

It would be very hard to quantify the "C" in the IPARC equation if "I" is one of these indices, right? Would it be better to have this section in chapter 1?

**Comment by MatthewHeun** [comment]
I don't quite understand the first question. But I think moving the section on indices to Ch1 may have merit and should be discussed.

**Comment by jgvanantwerp** [comment]
Pedagogically, I think chunking chapters 1 and 2 as they are makes sense.
