### ISSUE TITLE
Animal Populations?

### ISSUE THREAD

**Issue by MatthewHeun** [MatthewHeun/MCBook2021#176]
Tania Sousa writes:

I think it is confusing having "animal populations" here [first subsection of Ch3]. Why don't you put it in the chapter about impacts?

**Comment by MatthewHeun** [comment]
This is a comment that Jeremy should probably decide. Maybe we should interpret this question as: "we should do better at motivating why animals are discussed in the population chapter if the P term is human population."

**Comment by jgvanantwerp** [comment]
A) it's about A population.
B) the decreases we observe are a result of human population (increases). I think that ties it more strongly to the Population chapter than to the Impacts chapter. Placed where it is, it does provide a nice bridge.
Yes, we can do more to motivate.
