### ISSUE TITLE
Impact of high population densities?

### ISSUE THREAD

**Issue by MatthewHeun** [MatthewHeun/MCBook2021#180]
Tania Sousa writes:

High population densities allow for more natural space to be preserved :-)

**Comment by MatthewHeun** [comment]
This comment is in Section 3.2.4 (Distribution of population). High population density will exclude animal species in the densely populated area. But Tania is saying that perhaps more natural space can be preserved elsewhere? We should discuss this nuance, perhaps in a footnote.

**Comment by jgvanantwerp** [comment]
I think we need to double down on the "sparing vs sharing" paradigm.
Throughout the book but especially in chapter 10.

**Comment by MatthewHeun** [comment]
Given @jgvanantwerp comment above, I'm assigning to him to address.

**Comment by jgvanantwerp** [comment]
Add comment to chapter 3 about sharing vs sparing and point to chapter 10.
