### ISSUE TITLE
IPARC in each chapter

### ISSUE THREAD

**Issue by jgvanantwerp** [MatthewHeun/MCBook2021#183]
I think it would be helpful to actually see eq 1.1 at the top of each chapter.

**Comment by MatthewHeun** [comment]
The IPARX equation is now at the top of Ch1-Ch6. This addition has been implemented via a new macro in book.Rnw.

We can remove the equation and nearby text by commenting the text in Ch2-Ch6 at a later date, if we decide to walk this back.
