### ISSUE TITLE
chapter 5 - Grawe

### ISSUE THREAD

**Issue by jgvanantwerp** [MatthewHeun/MCBook2021#196]
More later, but I noted that 4 of the 5 time series graphs seem to have the wrong units on the y axis if we’re trying to understand R.  R is a per unit of GDP concept.  Figure 5.7 has use/GDP on the y axis, and low and beyond the trend is negative over time!  Wonderful news that points to possible paths forward.  By contrast, the other 4 time series plotted in this chapter either plot resources or resources per person.  It sure looks like if you matched the units to the topic of the chapter (that is, the concept of R) by presenting the same data relative to GDP, they too would have negative slopes.  The net result is to paint a picture that will lead many students to think R has increased in time when in fact the reverse is true.  I’d recommend transforming all of the y variables in these plots to represent the concept in question—resources/GDP.

**Comment by jgvanantwerp** [comment]
More from Nathan: "Having now read the chapter, I’m not sure all of the graphs need to be transformed.  I can see a potential storyline of “use is up so that you might think R is rising…but wait!”  Still, I think having 80% of the graphs focus on use or use/person and only 1 showing an R-like concept takes that rhetorical approach too far, leaving it possible that a lazy reader will remember all of the upward sloping use time series. Or maybe thinking “energy is different; most R’s slope up over time.”

**Comment by MatthewHeun** [comment]
As I looked at the chapter, the only graph that would benefit from Nathan's suggestion is the material use graph. I made a graph of material use per GDP. It looks like this:

<img width="733" alt="image" src="https://user-images.githubusercontent.com/3308246/147508045-e7a8db0a-a475-4a90-8034-d742a5d506dd.png">

I also added some commentary around the graph. 

I'm closing this issue now.
