### ISSUE TITLE
Sort out the PM story

### ISSUE THREAD

**Issue by MatthewHeun** [MatthewHeun/MCBook2021#197]
About this sentence in Section 8.3:

Problems in urban centers intensified with the introduction of early (dirty) internal combustion engines.

Paul Brockway wrote:

Not quite true. In the 1950s London smog was also due to home burning of coal for example and industrial processes. We still had power stations in cities then.  https://en.wikipedia.org/wiki/Pea_soup_fog
As a result we had new laws. 
But PM pollution remains a problem from cars, at least in the UK cities. 
We are introducing clean air zones as a result to tackle the transport emissions. https://tfl.gov.uk/modes/driving/ultra-low-emission-zone 

We need to revisit this sent

**Comment by MatthewHeun** [comment]
JVA wrote this section, so I'm asking him to revisit this.

**Comment by jgvanantwerp** [comment]
"Jeremy requested the history of urban air quality be added to Ch8. I'm not familiar with that history (or at least don't know what Jeremy is thinking). Maybe a pointer or help would be good. Or maybe JVA can draft a paragraph or two?" from #126.

**Comment by jgvanantwerp** [comment]
"Particulate Matter is mentioned as a negative effect of Transport (and a sustainability challenge) in Ch8.

Can JVA provide pointers to a few resources for PM pollution? Maybe some data?" from #127
