### ISSUE TITLE
double check figure 9.2

### ISSUE THREAD

**Issue by jgvanantwerp** [MatthewHeun/MCBook2021#198]
There's a spike in 2007. I went back and perused the original data. I didn't *see* that spike looking at the numbers. Of course, there has been some manipulation of the data to get form the original numbers to the plot. what is causing the spike?

**Comment by MatthewHeun** [comment]
I see that the spike *is* in the original data.

Here is the graph in the book:

<img width="829" alt="image" src="https://user-images.githubusercontent.com/3308246/145653408-fcda32a7-26a9-4a38-9ca7-b8a116a6d0c7.png">


Here is the graph I made in Excel (on the "Example Fig. 9.2" tab in file "Crippa et al 2021.xlsx"):

<img width="356" alt="image" src="https://user-images.githubusercontent.com/3308246/145653432-9deae1ab-d1d7-40f1-9786-75d5561a228d.png">
