### ISSUE TITLE
Does FIRE really work?

### ISSUE THREAD

**Issue by MatthewHeun** [MatthewHeun/MCBook2021#203]
In Sectio 12.2.2, Paul Brockway writes:

not sure that strategy [FIRE] lowers their impact on the planet. they just earn $1M/year for 10 years then retire and live high carbon lifestyles. i am not sure the evidence is there that the early retirees have frugal lifestyles

**Comment by MatthewHeun** [comment]
The question for me is "what is the point of comparison?" An individual who lives the $1M/year lifestyle for 40 years of a career? Or an individual who lives the $1M/year lifestyle for 10 years and $0M/year for 30 years thereafter? These paragraphs should be more clear about the point of comparison.

**Comment by jgvanantwerp** [comment]
Make MKH comment a project.

**Comment by MatthewHeun** [comment]
Added Project P12.7.
