### ISSUE TITLE
Different Tesla photo?

### ISSUE THREAD

**Issue by MatthewHeun** [MatthewHeun/MCBook2021#206]
In reference to Fig. 12.2(a), Paul Brockway asks:

can you show a Tesla that is not so shiny / one on the road.

**Comment by MatthewHeun** [comment]
I know JVA loves that photo. Maybe Paul's question should be taken from the reader's POV. Readers will not have the affinity for the car that JVA has. And readers may be confused by the iridescent color as well as the off-road location. These are things to consider.

**Comment by jgvanantwerp** [comment]
Caption updated.
