### ISSUE TITLE
42% or 42 %

### ISSUE THREAD

**Issue by MatthewHeun** [MatthewHeun/MCBook2021#207]
Spacing (or not) before "%" is inconsistent throughout the book. We need to pick one and stick with it. 

I don't care and could go with either.

JVA to decide and MKH to implement.

**Comment by jgvanantwerp** [comment]
42% no space. final offer.

**Comment by MatthewHeun** [comment]
I did a search and replace on "~\%" and " \%". That should take care of everything, but we should be vigilant. I'm closing for now.
