### ISSUE TITLE
Include a soil degradation map?

### ISSUE THREAD

**Issue by MatthewHeun** [MatthewHeun/MCBook2021#210]
In Section 9.2.2, Paul Brockway said:

coudl add a global map like this one: https://www.pinterest.com/pin/69524387969004713/

**Comment by MatthewHeun** [comment]
Perhaps we could add a soil degradation map, but we would need to deal with copyright issues. ggplot has the capability to draw maps, so if we think a map is important enough AND if we could find that data, I would be happy to make a figure with the soil degradation data.

**Comment by jgvanantwerp** [comment]
The particular one he referenced states it is an "unpublished map." Somewhat ironic. I'm generally not in favor of things that are of high/medium/low concern -- to who? and why? too subjective.

We mention soil degradation. What does a map add? (Could be scale of the problem. "It's local for me." )
