### ISSUE TITLE
Sustainability metrics?

### ISSUE THREAD

**Issue by MatthewHeun** [MatthewHeun/MCBook2021#211]
Paul Brockway suggests 

Metrics --> Sustainability metrics 

for the title of Section 9.3.1.

**Comment by MatthewHeun** [comment]
If we change this section title here, we may want to change it in other chapters, too.

**Comment by jgvanantwerp** [comment]
Yep. Let's do it. Easy fix.

**Comment by MatthewHeun** [comment]
I made this change. Section 9.3.1 was the only place where this change was required. No other sections are titled "Metrics".
