### ISSUE TITLE
Clarify agriculture metrics

### ISSUE THREAD

**Issue by MatthewHeun** [MatthewHeun/MCBook2021#214]
In Section 10.1.2 in response to "Joules per food calorie (that is EROI)," Paul Brockway wrote:

thats the inverse of EROI

**Comment by MatthewHeun** [comment]
JVA should clarify the purpose of this sentence. And is Joules the energy input to the farming system? Or is it something else? Probably would be good to clarify.

**Comment by jgvanantwerp** [comment]
Changed "For example, with respect to agriculture, we could attempt to maximize
calories per acre, pounds of food per acre, number of people fed per acre, \emph{or} 
Joules per food calorie (that is, EROI). "

to "For example, with respect to agriculture, we could attempt to maximize
calories per acre, pounds of food per acre, number of people fed per acre, 
\emph{or} the EROI of agriculture. "
