### ISSUE TITLE
Need sense of scale for Fig. 10.2

### ISSUE THREAD

**Issue by MatthewHeun** [MatthewHeun/MCBook2021#216]
Regarding Fig. 10.2, Paul Brockway notes:

i dont really get a sense of scale. the GtC for example wodul mean more if we knew the scale of GtC emitted each year. also how much do the sinks absorb each year? are they gettign bigger, like 10GtC each year or have they reached steady state? or are they getting smaller like losing -10GtC per year.

**Comment by MatthewHeun** [comment]
Maybe a way to address this issue is to include annual global CO2 emissions in the figure caption?

**Comment by jgvanantwerp** [comment]
Sure.

**Comment by MatthewHeun** [comment]
I added a note to the caption. JVA to review and close this item if it looks fine.

**Comment by MatthewHeun** [comment]
Added "For context, Figure 2.5 shows annual carbon emissions are 36.4 GtCO2/year (2019), a small fraction of total carbon stored in the biosphere." to caption on Fig. 10.2
