### ISSUE TITLE
Figure 3.3 (World3 causal loops)

### ISSUE THREAD

**Issue by jgvanantwerp** [MatthewHeun/MCBook2021#219]
Near Industrial Investment and Population there are parentheses with a plus sign: (+) 
Add what this means to the caption of Figure 3.3.

**Comment by MatthewHeun** [comment]
Solved by deleting the "(+)" symbols. There probably should be more (+)  and (-) notations to indicate reinforcing (+) or balancing (-) loops. But those aren't shown in the original diagram. So best to remove the notations altogether.
