### ISSUE TITLE
Figure 1.1: tikz

### ISSUE THREAD

**Issue by MatthewHeun** [MatthewHeun/MCBook2021#220]
If we're reverting to the oval diagram, we can make it in Tikz to look more like the causal loop diagram.

**Comment by jgvanantwerp** [comment]
shift the colors clockwise one step so that gold is economic, green is environmental, and purple is social.

**Comment by MatthewHeun** [comment]
> shift the colors clockwise one step so that gold is economic, green is environmental, and purple is social.

I can do that.

**Comment by MatthewHeun** [comment]
JVA should check the Venn diagram. If it looks good now, close this issue.
