### ISSUE TITLE
search for contamination

### ISSUE THREAD

**Issue by jgvanantwerp** [MatthewHeun/MCBook2021#221]
I just did a new build of the book and there were several vestigial "contamination intensities" 
I fixed what I found.
Search globally for "contamination" and evaluate if any need to be changed.

**Comment by jgvanantwerp** [comment]
Also search for "pillar" and consider changing to "area" or "domain" to go with the new figure 1.1.

**Comment by MatthewHeun** [comment]
I did a global search for "contamination" and changed most to "impact".

I searched for pillar and changed to "area" in most places.
