### ISSUE TITLE
Add carbon take-back obligation to the list of carbon mitigating strategies

### ISSUE THREAD

**Issue by jgvanantwerp** [MatthewHeun/MCBook2021#222]
https://www.aiche-cep.com/cepmagazine/december_2021_cep/MobilePagedArticle.action?articleId=1747858&amp;app=false#articleId1747858

Does this really go in chapter 6? or maybe 11?

**Comment by MatthewHeun** [comment]
For now, I put this in Ch6, as it seemed like a better fit. But we can move it if we think Ch11 will be better.
