### ISSUE TITLE
Nuclear #1 - Grawe

### ISSUE THREAD

**Issue by jgvanantwerp** [MatthewHeun/MCBook2021#226]
“Hydro, solar, and wind are primary energy sources. So are coal, crude oil, and natural gas. In contrast, gasoline is a refined fuel.”  What about nuclear?  (I think it’s primary, but maybe I am missing something about the way the technology works.

I changed the relevant sentences in section 5.1 to read
"Hydro, solar, and wind are primary energy sources. 
So are coal, crude oil, and natural gas.
In contrast, gasoline is a refined fuel. 
As such, it is the \emph{product} of 
a refinery that converts crude oil to refined fuels. 
_Likewise, natural uranium is a primary energy source that must be converted into 
a uranium fuel before it can be used to generate electricity in a nuclear power plant._
The refinery or nuclear-fuel enrichment process can be evaluated by their
energy return on investment (EROI). (See Section~\ref{sec:masterE}.)"

**If MKH is OK with this change, close the issue.** The italic text is new. The last sentence is modified from the previous version.

**Comment by MatthewHeun** [comment]
I made minor edits to the JVA edits and am happy with the result. So I'm closing the issue.
