### ISSUE TITLE
Figures - Grawe

### ISSUE THREAD

**Issue by jgvanantwerp** [MatthewHeun/MCBook2021#227]
It took me a long time to find Fig 5.1.  Wonder if it can be moved to first reference.

**Comment by jgvanantwerp** [comment]
Brockway commented on this too. This is a reminder for us to go back and look at floats right before we pull the trigger. I think we can tighten things up a bit, maybe have two on one page. Figures 10.2 and 10.3 are especially bad -- they float until after the projects in chapter 10.

**Comment by MatthewHeun** [comment]
We *could* fiddle with the position of figures and tables. But in my experience, it is rarely worth the time spent. The publisher always fiddles with figure and table positioning , anyway.

**Comment by MatthewHeun** [comment]
If JVA agrees, he can close this issue. I'm assigning to JVA now.
