### ISSUE TITLE
Table 5.1 and related discussion - Grawe 

### ISSUE THREAD

**Issue by jgvanantwerp** [MatthewHeun/MCBook2021#228]
**Grawe wrote** "I’m not sure [Table] 5.1 and related discussion is particularly on point.  That table uses a definition of “critical” that is as much about “is there supply risk through monopoly/does the EU have internal access to this thing” as about its use.  (See methods here.) I’ll bet that’s why Petroleum isn’t considered critical.  The fact that the EU does or doesn’t have something within its borders or that something is produced by a more or less concentrated industry doesn’t seem particularly relevant to your discussion."

**I edited the discussion of Table 5.1 to be**
"Although any raw material can be essential for a given product,
the European Commission maintains a list of Critical Raw Materials (CRMs)\index{materials!critical!raw}
with special importance 
across a wide range of industries.
See Table~\ref{tab:CRMs} for critical materials and industries for the European Union.
Notice the \emph{large number} of resources considered ``critical.''
Energy is important for making an economy run but so are material resources.
Another interesting feature of Table~\ref{tab:CRMs} is the \emph{breadth of applications}; 
most of the critical materials are used throughout the economy.
A material may be critical to a region or economy for any number of reasons:
breadth of application, 
lack of internal production capability, 
etc.
Each region or economy will have its own list of CRMs.
The point isn't which materials are critical, it's that economies depend deeply on
a large number of raw materials."

**If MKH is fine with this edit, close the issue.**

**Comment by MatthewHeun** [comment]
I'm fine with JVA edits. I made a couple minor changes and am happy to close this issue.
