### ISSUE TITLE
Figure 5.2 - Grawe

### ISSUE THREAD

**Issue by jgvanantwerp** [MatthewHeun/MCBook2021#229]
**Nathan wrote** "Fig 5.2—I’m not sure this is relevant to the discussion of this section.  If we’re extracting any resources (strong) or more than are generated (weak), then the extraction is unsustainable.  The fact that the extraction per person might be falling, even rapidly, wouldn’t change that.  I wonder if Fig 5.2 belongs (along with Fig 5.1) up with the first reference to Fig 5.1.  At that point in the argument, you are noting how much we use.  In section 5.2 you can refer back to Figs 5.1 & 5.2 and note that they aren’t strongly sustainable."

**JVA added this to the second-to-last paragraph of Section 5.2**
"Although a falling global population might \emph{help} humanity to become 
sustainable, Figure~\ref{fig:per_capita_material_use} indicates that won't be
enough. 
Affluence would still be a driver of unsustainability."

**MKH can review and close.**

**Comment by jgvanantwerp** [comment]
Did Nathan Grawe miss the fact that Figure 5.2 shows rising per capita resource use or is he posing a counterfactual?

**Comment by MatthewHeun** [comment]
I made minor edits and am now closing.
