### ISSUE TITLE
Chapter 2 question about financial value needs an end.

### ISSUE THREAD

**Issue by MatthewHeun** [MatthewHeun/MCBook2021#23]
* Give some specifics?
* Reference the field of Ecological Economics, which focuses on defining financial value of ecosystem services. Some think the field is rubbish, because the idea is bogus in the first place.
* But money is the way we make tradeoffs in our society. Is that a good way to make tradeoffs? A just way to make tradeoffs? The right way to make tradeoffs?

Contrast to Mt. Rushmore? Who thought this was a good idea to do to a mountain? (Mountain top removal mining?)

**Comment by jgvanantwerp** [comment]
MKH to clarify *which* question this is. (Maybe it's already been fixed?) Then either pass it back to me or close the issue.

**Comment by MatthewHeun** [comment]
The question in question seems to be gone now. I'm closing the issue.
