### ISSUE TITLE
Consider adding references about the time scale for sustainability

### ISSUE THREAD

**Issue by MatthewHeun** [MatthewHeun/MCBook2021#230]
About Chapter 1, Zeke says:

Some useful references for the time-scale over which sustainability must be assessed:
·         Soil carbon debt of 12,000 years of human land use https://doi.org/10.1073/pnas.1706103114
·         Mammal diversity will take millions of years to recover from the current biodiversity crisis https://doi.org/10.1073/pnas.1804906115

**Comment by MatthewHeun** [comment]
Covered in #230

**Comment by jgvanantwerp** [comment]
done.

**Comment by jgvanantwerp** [comment]
Although humans seem to have inherent cognitive difficulties in planning for 
time scales significantly longer than the human lifespan, 
\emph{strong} sustainability is achieved only if the answer is
``indefinitely'' or ``forever.''
**Our current sustainability crisis has been thousands of years in the making~\cite{Sanderman2018}
and will likely require millions of years to recover~\cite{Davis11262}.**
A \emph{weak} sustainability criterion is sustainability over a long (by human standards)
time frame, perhaps 50 years, which is on the order of one human adulthood.
