### ISSUE TITLE
Questioning Daly

### ISSUE THREAD

**Issue by MatthewHeun** [MatthewHeun/MCBook2021#232]
Zeke said:

I like that the Brundtland Report definition of sustainable development is followed by Daly’s framing. However, I think Daly’s framing is somewhat mechanistic in defining sustainability in terms of macroscopic stocks and flows of resources (also anthropocentric), whilst neglecting the conservation of biodiversity etc.

**Comment by MatthewHeun** [comment]
JVA to decide how to deal with this comment, possibly by closing, because we already excised the Herman Daly definition of sustainability from the book.

**Comment by jgvanantwerp** [comment]
Agree that we should close without change because we've excised Daly from chapter 1.
(with the reason that Daly's definitions were not self-consistent with either strong or weak sustainability.)
