### ISSUE TITLE
Caveat need to reduce meat and dairy production

### ISSUE THREAD

**Issue by MatthewHeun** [MatthewHeun/MCBook2021#236]
Zeke said:

In section 9.4 you state that “No ecosystem can function properly without animals”, which is correct, however I think that there needs to be a caveat, namely that a shift to sustainable agroecosystems (containing livestock) will reduce meat & dairy production. Though this is perhaps covered by the closing quote from Michael Pollen.

**Comment by jgvanantwerp** [comment]
part of #289?

**Comment by jgvanantwerp** [comment]
improvements in agricultural practices are likely to raise costs, which will decrease consumption. This is noted.
