### ISSUE TITLE
Include potential natural vegetation

### ISSUE THREAD

**Issue by MatthewHeun** [MatthewHeun/MCBook2021#238]
Zeke says:

Page 144
A good way to illustrate the opportunity cost of human land use is a map of the potential natural vegetation (according to some classification system), here’s a great one from 1970: http://www.codex99.com/cartography/images/national/vegetation_1970_lg.jpg

**Comment by MatthewHeun** [comment]
Perhaps this is a good way to beef up Ch10?

**Comment by jgvanantwerp** [comment]
we've done a revision on chapter 10. I think Zeke's suggestion is good but doesn't add all that much on top of 10.2.
