### ISSUE TITLE
Use Meadows leverage points in a system?

### ISSUE THREAD

**Issue by MatthewHeun** [MatthewHeun/MCBook2021#239]
Zeke says:

Chapter 11:
 
I like the framing, and focus on four archetypal examples, but would it first be worth introducing Donella Meadows 12 leverage points, places to intervene in a system? With points 11 and 12 being the discussion of the pre-analytical framework in Chapter 1 above.

![image006](https://user-images.githubusercontent.com/3308246/147371389-72208cb4-0896-49ee-a8a3-11efc5b595e5.png)

**Comment by MatthewHeun** [comment]
This content (leverage points) would go well in a chapter on systems thinking and complexity theory. We have decided against such a chapter (drafted for an early version of the book). So I'm not sure what to do with this comment.

**Comment by MatthewHeun** [comment]
I'm inclined to *not* make any changes in response to this comment. If JVA agrees, he can close this issue.

**Comment by jgvanantwerp** [comment]
agree. (Among many considerations, I'm not entirely sure that I agree with the relative moment given to each intervention.)
