### ISSUE TITLE
Substitution - Grawe 

### ISSUE THREAD

**Issue by jgvanantwerp** [MatthewHeun/MCBook2021#241]
**Nathan wrote:** "p. 64 The paragraph starting “Substitution is possible when the two resources in question are identical” focuses only on industrial use.  We have similar principles of substitution in consumption.  I could get enjoyment by taking a joy ride or by watching a sunset, for example.  But here we see substitution doesn’t depend on the identical nature of the resources so much as the overlapping uses.  (Here, I get joy from either activity even though the inputs are very different.)  I’d argue that the **“ovelapping purpose/function” framing**—they serve similar purposes—**actually better describes what you say about industrial resources** (steel vs. plastics, eg) and would allow you to broaden this paragraph a good bit with just a sentence noting the application of the idea to consumption as well as production." (emphasis added.)

**In response, JVA added** "(This section focuses on substitutability of resources in manufacturing or production.
For a related discussion of substitution in consumption, see Question~Q\ref{chap:resource_intensity}.{question:consumption_substitution}.)" AND discussion question Q.5.16.

**Decision**: do we keep the framing of material properties in the chapter and leave the concept of functionality in the discussion question OR do we revise Section 5.3 to define substitutability differently?

**Comment by MatthewHeun** [comment]
I'm fine with keeping the framing of Ch5 as is (on manufacturing processes). I made a few small edits and am closing this issue.
