### ISSUE TITLE
China/WTO - Grawe

### ISSUE THREAD

**Issue by jgvanantwerp** [MatthewHeun/MCBook2021#242]
**Nathan wrote** "p. 67 “China’s entrance into the World Trade Organization in late 2001 led to …” seems a pretty strong causal claim.  I really doubt the WTO had a lot to do with it. I think China was getting richer and would have done so (to a great degree even if somewhat less so) even if the WTO would have snubbed them.  The growth in economic activity in the developing world (perhaps led by China) seems a plausible cause for what we see in the graph.  But the WTO causal connection seems a stretch."

In the MCFrame box discussing Figure 5.6, 
**JVA changed** "China's entrance into the World Trade Organization in late 2001 led to a noticeable rise in per-capita energy consumption." 
to
"Economic growth in the developing world, particularly in China, led to a noticeable rise in per-capita energy consumption starting in 2001."
We could delete the parenthetical. We could add that China's entrance into the WTO was emblematic of that growth (but I think that's unnecessary).
**MKH to review** and close issue as he sees fit.

**Comment by MatthewHeun** [comment]
I like Jeremy's modification. Also, I downplayed the China/WTO angle in another part of the book. I'm happy with how this has been handled and am closing the issue.
