### ISSUE TITLE
Last Q in Ch5 needs editing

### ISSUE THREAD

**Issue by MatthewHeun** [MatthewHeun/MCBook2021#243]
The end of the question reads:

        In each of the following categories, what is an unsustainable:
        recreational activity, household utility, food, land use that \emph{you do}?
        Think of a more sustainable alternative that you could substitute.
        How are your sustainable and unsustainable choices similar?
        How are they different? \label{question:consumption_substitution}

Maybe the colon needs to be removed? Seems like JVA should take an editing pass across this question.

**Comment by jgvanantwerp** [comment]
I've implemented this change to the first sentence.

> What is an unsustainable recreational activity, household utility, food, and land use that \emph{you} do or use?
If MKH is OK with this change, close issue.

**Comment by MatthewHeun** [comment]
Hmmm. I think the question remained confusing. I did a deep edit on the last part of the question. 

JVA to confirm the question is now clearer and close.

Or edit further.

**Comment by jgvanantwerp** [comment]
great!
