### ISSUE TITLE
Additional questions/projects

### ISSUE THREAD

**Issue by jgvanantwerp** [MatthewHeun/MCBook2021#245]
Add benefit corp to chapter 11.
project to verify Strong Towns tax assertions -- chapter 10.
Strong Towns Black Friday parking -- chapter 10 project.
Add mountain lion story to sharing/sparing question (ch 10).
Fugitive emissions/efficiency/EROI comparison electric vs. natural gas -- chapter 5?

**Comment by MatthewHeun** [comment]
Russian family that fled to woods of Siberia during communist prosecution. Old Bretheren who were nearlly completely off the grid. They were dirt poor. Daughter died in 2017.

Is this a model for sustainability or not?
