### ISSUE TITLE
"far in the future"

### ISSUE THREAD

**Issue by jgvanantwerp** [MatthewHeun/MCBook2021#264]
Gregor wrote:
"p. 4 the phrase 'it may seem like the consequences of not becoming sustainable are so far in the future' may not pull its weight any more as much in a world where changes in the environment can increasingly be experienced locally (and by reading the news) by the average reader of this book. But I totally see what you mean. Perhaps add a sentence that some changes shrink the time scales, while others are still very much on that time scale, like meters of sea level rise, that will happen over centuries?"

In response, I added the bolded text to the paragraph
 (Added "Any quick survey... improve our sustainability in the near term"):

Sustainability is difficult for two additional reasons. 
First, it may seem that the changes required to achieve sustainability are so 
massively overwhelming that they shouldn't even be attempted.
Second, it may seem like the consequences of not becoming sustainable are so far
in the future that there is neither urgency nor immediate payback.
Neither of these views is true.
**Any quick survey of current news headlines indicates that we are already 
experiencing the effects of not being sustainable, across a variety of 
dimensions --- environmentally, economically, \emph{and} socially.
There are many reasonable and simple things that can be done to improve our 
sustainability in the near term.**
The deep changes needed for **long-term** sustainability are urgently needed precisely because
they are long-term investments.
The sooner we begin making those investments, the sooner we'll begin reaping the
rewards and the greater those rewards will be.

**If MKH is OK with the change, he can close the issue.**

**Comment by MatthewHeun** [comment]
This looks really good. I made one small change and am happy to close the issue.
