### ISSUE TITLE
end of section 1.1

### ISSUE THREAD

**Issue by jgvanantwerp** [MatthewHeun/MCBook2021#265]
Revised text (changes in bold):

**Our framework for describing sustainability challenges is illustrated by data.**
Thus, readers can expect graphs, tables, and other numerical representations
of the state of our world as it relates to sustainability.
Part~\ref{part:IPARX} (Chapters~\ref{chap:introduction}--\ref{chap:impact_intensity})
shows mostly data from the world in aggregate.
Part~\ref{part:sustainability_challenges} shows data mostly from the U.S.\footnote{
  Readers are encouraged to remember that the U.S.\ is atypical **in many ways.
  Sociologically, the U.S.\ is WIERD (Western, industrialized, educated, rich, and democratic).
  Additionally, the U.S.\ has a low population density and lots of resources.
  While our framework for sustainability thinking is universal, the data used for 
  illustration may not always apply to the rest of the world.**
}, 
because it is the home country of the authors and 
because it has better data coverage than most countries 
regarding energy and carbon emissions.
Behind the facts and data are important concepts related **to human choices.** %consumer choices in human economies.
**% Readers can watch for these important categories 
% throughout the book:
% discretionary vs.\ non-discretionary choices, 
% essential vs.\ non-essential economic activities,
% goods vs.\ services, and
% sufficiency vs.\ extravagance.**
The remainder of this chapter summarizes key themes of the book.

(Side note: does the remainder of chapter 1 do more than summarize key themes?)

**MKH to review and approve/close issue.**

**Comment by MatthewHeun** [comment]
Made a few small edits. Otherwise, looks very good! Closing now.
