### ISSUE TITLE
Do a final check to populate the Index.

### ISSUE THREAD

**Issue by jgvanantwerp** [MatthewHeun/MCBook2021#267]

**Comment by MatthewHeun** [comment]
MKH taking this over for the final push. We decided the following:

* Minimal use of \emph{}.
* Use \textbf{} for key words and terms, first time they appear. Signal this approach in the preface. 
* Add \index{} items at the same time. 
* All \text{bf} terms will be in the index.

**Comment by MatthewHeun** [comment]
Proposed bold terms (first time used):

**Comment by MatthewHeun** [comment]
All items on my list of "bold first time" terms have been entered into the index.

Next step: go through the text itself.

**Comment by MatthewHeun** [comment]
I think I am done with this.
