### ISSUE TITLE
add a table of key terms to the book

### ISSUE THREAD

**Issue by jgvanantwerp** [MatthewHeun/MCBook2021#278]
It could be in chapter 1. 
It could come after the Preface (which would have the advantage of not interrupting the flow of chapter 1).
The table should contain a note suggesting that it be printed or copied and kept at hand as readers read through the book.

**Comment by MatthewHeun** [comment]
Added the stub of a table to the Preface in a section titled 

\section*{What you should put into this book}

EROI is the first (and only at this point) term in the table.

**Comment by MatthewHeun** [comment]
This table is now in mostly-final format. So closing this issue.
