### ISSUE TITLE
add summary to chapter 4

### ISSUE THREAD

**Issue by jgvanantwerp** [MatthewHeun/MCBook2021#279]

**Comment by jgvanantwerp** [comment]
done. Does it look like a summary now? (Note chapter 3 also has a summary. Haven't done 2 yet.)

**Comment by MatthewHeun** [comment]
This looks great. I made a few minor changes to Ch3 and Ch4 summaries, especially regarding the use of macros and ~. JVA may want to take a look at the style. I'm leaving this issue open as a reminder of Ch2 summary.

**Comment by jgvanantwerp** [comment]
that's #274
