### ISSUE TITLE
Figure 2.3 to per kcal instead of per kg

### ISSUE THREAD

**Issue by jgvanantwerp** [MatthewHeun/MCBook2021#280]
Grawe: "Was curious about representation of GHG emissions—why not by calorie (rather than kg given that my diet has a calorie rather than kg requirement.)  Saw this data that might be an option: https://ourworldindata.org/grapher/ghg-kcal-poore"

The reference for Fig 9.3 is https://ourworldindata.org/environmental-impacts-of-food
which has a radio button to show the data per kg or per kcal (and even per 100g of protein). When you click the radio button, it shows the Poore data.
1. change the graph to be in per kcal.
2. change the caption to read "Food CO2 emissions per kcal of food. Source: Poore []. See Ritchie and Roser [124] for similar data per kg."

**Comment by MatthewHeun** [comment]
DONE.
