### ISSUE TITLE
Add expected carbon savings to Table 12.1

### ISSUE THREAD

**Issue by jgvanantwerp** [MatthewHeun/MCBook2021#287]
One piece of the framework that I thought was missing was a sense that these choices have magnitudes. 
In Ch 12 one could note the GHG savings of a modest range of choices—to exemplify the need to think through those magnitudes when selecting a set of “sentences” to pursue.

**Relative to a per-capita carbon budget taken from the HDI graph,** how much does each activity cost or save?
Perhaps get Anjana to work on this?

**Comment by MatthewHeun** [comment]
I sent an email to Anjana to do some research for this task.

**Comment by MatthewHeun** [comment]
I'm thinking about a graph. Crude (Excel) graph looks like this:

<img width="358" alt="image" src="https://user-images.githubusercontent.com/3308246/149700606-dc9c592f-7180-4fd8-85c0-6130df0e07d2.png">

What does JVA think? Graph? Or add to table?

**Comment by jgvanantwerp** [comment]
Given that the Table is already nearly full width, I think i'm leaning toward the graph.
Some critique of the crude graph above.
"50 miles to work" is probably not "per year." Is it per day? Maybe: "eliminating a daily commute" or "a carbon-free commute"?
I'm assuming the caption explains the parameters and assumptions. For instance, the assumptions behind "smaller home" (square-foot reduction, location, source of heating and cooling)
"Accord" capitalized. (Why Honda Accord and Ford F-150? Does it have to be those exactly?)
Fly from where? Maybe: "eliminate 6000 km of passenger air travel"?

**Comment by MatthewHeun** [comment]
Here is a version of the graph with detailed caption.

<img width="761" alt="image" src="https://user-images.githubusercontent.com/3308246/149853201-f7be0d1d-aca1-4427-8756-a976d61a71a8.png">

I have also added a project to Ch12 that asks students to think of other actions for the rows of Table 12.1; then calculate emissions savings.

<img width="779" alt="image" src="https://user-images.githubusercontent.com/3308246/149853092-d8275573-711d-415d-bfaa-65ea34fbcac8.png">

For context, here is Table 12.1:

<img width="747" alt="image" src="https://user-images.githubusercontent.com/3308246/149853248-6f009611-2974-40d8-8b04-1518f351a43d.png">

Reactions from JVA are welcome.

**Comment by jgvanantwerp** [comment]
What about showing doing the activity in red and not doing it in blue?
So, "commuting" would be side-by-side with "no commute."
Larger home/smaller home. (BTW, I still think a little more information is needed about the source(s), and assumptions that went into the calculations, particularly for the house.
chicken/steak.
Accord/F-150.
Flying/not flying.

**Comment by MatthewHeun** [comment]
Done. Now with multi-bar style. Added long caption to give context to calculations. Also added CO2 savings rates to caption.
