### ISSUE TITLE
"GDP is denominated in units of money"

### ISSUE THREAD

**Issue by jgvanantwerp** [MatthewHeun/MCBook2021#291]
chapter 4, line 285.

I think we talked about this before, but i'm double checking. GDP is $ not $/yr because we talk about affluence is the amount of GDP in a year??

**Comment by MatthewHeun** [comment]
I think it should be money per year. GDP is actually a rate. So maybe this:

GDP is denominated in units of money per time and is usually the sum of four annual terms,

**Comment by jgvanantwerp** [comment]
fixed and closed.
