### ISSUE TITLE
Rework exponential figure (Figure 1.2) to be the number of grains on the chessboard.

### ISSUE THREAD

**Issue by jgvanantwerp** [MatthewHeun/MCBook2021#299]
Y-axis is # of grains.
X-axis is squares.

**Comment by MatthewHeun** [comment]
Here is an example:

<img width="755" alt="image" src="https://user-images.githubusercontent.com/3308246/148709102-38af2441-9e9d-485e-96a1-8c65f23dc234.png">

Is this what we want?

**Comment by jgvanantwerp** [comment]
Yes, I think that's great!

**Comment by MatthewHeun** [comment]
OK. I commented the previous exponential graph and am closing this issue now.
