### ISSUE TITLE
Problems with agricultural "yield"

### ISSUE THREAD

**Issue by MatthewHeun** [MatthewHeun/MCBook2021#322]
Uko sez:

Q9.1” One common metric for agricultural productivity is yield, the amount of a crop produced per area.” I find this Q to be rather reductionistic. Yield per acre has been used as the basis for increasing concentration in agriculture at the detriment of small-scale farming and the detriment of more sustainable agricultural practices. Efficiency must incorporate the metric of soil health, which includes the microbe ecosystems of the soils. The metric of yield per acre has pushed agriculture into the use of chemical fertilizers, pesticides, and herbicides which has contributed to massive decline of soil health. Also, the comment that “the most basic economic metric for agriculture is protability, that is, (net) prot per acre,” ignores the externality cost of soil degradation, pointing to the reductionist metric? 

Consider this point when doing the rewrite of Ch9. Do we want to critique yield in this discussion question? In the chapter itself?

**Comment by jgvanantwerp** [comment]
maybe we've revised the question since Uko saw it? To me (at least) it's clear that the point of the question is to question the one dimensionality of yield and $/acre as metrics.
