### ISSUE TITLE
Future generations and land use

### ISSUE THREAD

**Issue by MatthewHeun** [MatthewHeun/MCBook2021#324]
We owe it to future generations to preserve the best farmland for producing food. 

Add to Ch10. Under the efficiency metrics piece.

Sweep up in Ch10 rewrite.

===================

Uko's comment was:

 p. 163. The statement “Land is the primary source of energy, be it fossil fuel, biomass, or renewable.” I find to be a reductionist statement and thus not a good context for this section. This is also evident in the discussion of cropland that can be replaced by cutting down more forest, etc. That simply assumes that all cropland is equivalent which is not so. Furthermore, good cropland entails a healthy soil, and I would argue that prime farmland (cropland) should be zoned (preserved) as prime farmland in “perpetuity’ for future food needs as well as present food needs. We have not been able to give appropriate economic value to prime farmland and thus prime farmland continues to be lost to other forms of “development”. The decline of healthy soils is another externality that needs to be internalized for global food sustainability. If we were to do so, we would find that smaller scale farming would be more economically feasible because small scale farming is more effective in maintaining soil health.

**Comment by jgvanantwerp** [comment]
1. I need to make it clear that land as the source of energy and conversion of forests to cropland is the way things ARE. No value judgement.
2. Our best efficiency is obtained by preserving the best farmland. Add that to the efficiency section.
3. Discussion question about how to do (2). Loss of farmland is a negative externality (to future generations?). Thus we could pay people with the best land to say farming. What would be the unintended consequences of such a plan? (Vs. France's PLU, for example.)
