### ISSUE TITLE
retrofitting old buildings vs. design of new buildings

### ISSUE THREAD

**Issue by jgvanantwerp** [MatthewHeun/MCBook2021#327]
There are challenge and transition issues associated with old buildings and new buildings.
For old buildings, how do we get them to become more energy efficient. This question entails things like historic preservation and appropriate technology. But also there are ROI questions ($, energy, and emissions--embodied, construction, and operational).

For new buildings, how do we "up" the standard---PassivHaus, Living Building, etc. (This might be a good place to mention Joe Lstiburek.)

Given a set amount of dollars, is there more impact in fixing old buildings or putting money into new buildings?

**Comment by MatthewHeun** [comment]
I incorporated this idea via a question in Ch7.

\item Consider the sustainability challenges associated with old and new homes.
      For old homes, what does it take to make them more energy efficient? 
      Be sure to think about historic preservation value and technology 
      appropriate for old structures.
      For new homes, what does it take to implement standards for 
      higher system efficiencies and enhanced insulation?
      You might want to investigate the passive house movement, 
      the living building challenge, net zero homes and 
      Joe Lstiburek (Section~\ref{sec:stories_individual_actions}).
      Given a fixed amount of money, 
      do you suppose there is more sustainability impact 
      in improving old homes or investing in new construction?
