### ISSUE TITLE
How to handle end-of-sentence references

### ISSUE THREAD

**Issue by MatthewHeun** [MatthewHeun/MCBook2021#335]
We need a ruling from the first author 🙂.

I have been writing

(a) ``Capital'' refers to an improvement or building that is economically productive 
or valuable; see Chapter~\ref{chap:affluence}.

Looks like JVA has been writing

(b) ``Capital'' refers to an improvement or building that is economically productive 
or valuable. (See Chapter~\ref{chap:affluence}.)

Which does JVA prefer, (a) or (b)?

**Comment by jgvanantwerp** [comment]
I prefer A.

From: MatthewHeun ***@***.***>
Sent: Thursday, January 13, 2022 7:32 PM
To: MatthewHeun/MCBook2021 ***@***.***>
Cc: Jeremy VanAntwerp ***@***.***>; Assign ***@***.***>
Subject: [MatthewHeun/MCBook2021] How to handle end-of-sentence references (Issue #335)


We need a ruling from the first author 🙂.

I have been writing

(a) ``Capital'' refers to an improvement or building that is economically productive
or valuable; see Chapter~\ref{chap:affluence}.

Looks like JVA has been writing

(b) ``Capital'' refers to an improvement or building that is economically productive
or valuable. (See Chapter~\ref{chap:affluence}.)

Which does JVA prefer, (a) or (b)?

—
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_MatthewHeun_MCBook2021_issues_335&d=DwMFaQ&c=4rZ6NPIETe-LE5i2KBR4rw&r=MWoc9gmyzY36X47hDGu-aA&m=QuLjQust3fdSfeMrxdvZbgbVGsF0k5-vuYLvuaSG7PWPc8xV6jTKkRJ6OARPegZh&s=AjrxzzfAksUeFgrsczaLKkJ5ZF3tftrpgJopiF7iESQ&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ALOOF3EOQBLZR7UTD4O6QMTUV5VHZANCNFSM5L5LBKQA&d=DwMFaQ&c=4rZ6NPIETe-LE5i2KBR4rw&r=MWoc9gmyzY36X47hDGu-aA&m=QuLjQust3fdSfeMrxdvZbgbVGsF0k5-vuYLvuaSG7PWPc8xV6jTKkRJ6OARPegZh&s=n_qtcDWD4RnTNmC0Q5VpPFedUjSIL81dOdsHkECJBm8&e=>.
Triage notifications on the go with GitHub Mobile for iOS<https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMFaQ&c=4rZ6NPIETe-LE5i2KBR4rw&r=MWoc9gmyzY36X47hDGu-aA&m=QuLjQust3fdSfeMrxdvZbgbVGsF0k5-vuYLvuaSG7PWPc8xV6jTKkRJ6OARPegZh&s=LFtWdDfN29_QzoBVSFN99rqy5uJi04NId60onDVxLeE&e=> or Android<https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMFaQ&c=4rZ6NPIETe-LE5i2KBR4rw&r=MWoc9gmyzY36X47hDGu-aA&m=QuLjQust3fdSfeMrxdvZbgbVGsF0k5-vuYLvuaSG7PWPc8xV6jTKkRJ6OARPegZh&s=2tr6mWJJTfBtyA-BFsBhsGuOnly5zohEgzrWju8oNgk&e=>.

**Comment by MatthewHeun** [comment]
OK. I'll change to (a), as I review chapters this evening.
