### ISSUE TITLE
Another sentence could be simpler

### ISSUE THREAD

**Issue by MatthewHeun** [MatthewHeun/MCBook2021#338]
Ch3 contains this sentence:

In contrast to less dense, less impactful human use (that is, the ``sharing'' paradigm) 
%% https://english.stackexchange.com/questions/21104/hyphen-or-no-hyphen-when-modifying-an-adjective-with-an-intensifier-downtoner 
areas with concentrated human activity tend to exclude most animal species.

Perhaps because it is getting late, I can't find a good way to simplify it, so I'm throwing it to JVA.

**Comment by jgvanantwerp** [comment]
For example, high population density, characteristic of urban areas, enables
cost-effective mass transit, which reduces carbon emissions from transportation.
Concentrating human population into a few high-density areas excludes most animal
species from those locations.
In theory, concentration in a few spots allows \emph{other} areas to be ``spared,''
or dedicated for animal use.
In contrast, the ``sharing'' paradigm disperses human impact more broadly.
Chapter~\ref{chap:land_use_urban_planning} discusses in more detail the
land-sharing versus land-sparing paradigm. 
There is a strong connection between population density and land use.
What density is ``best'' for sustainability depends on which factors
are being considered; there is no one ``right'' answer.
