### ISSUE TITLE
Move a question about urban, suburban, rural to Ch10?

### ISSUE THREAD

**Issue by MatthewHeun** [MatthewHeun/MCBook2021#340]
Should this Ch3 question

\item Describe where you live. 
      Is it urban, suburban, rural, or would you describe it in some other way? 
      What do you like about the environment in which you live? 
      How would you make it different if you could?

be moved to Ch10?

**Comment by jgvanantwerp** [comment]
done.
I actually moved both question 3.9 and 3.10 to chapter 10. then i created a new question 3.9 about population density.
