### ISSUE TITLE
Do we need to slam other countries?

### ISSUE THREAD

**Issue by MatthewHeun** [MatthewHeun/MCBook2021#341]
This sentence in Ch4:

(Because GDP data are collected nationally but aggregated internationally, 
there is often skepticism of data provided by corrupt and/or authoritarian
regimes, in addition to the caveats about what GDP measures and what it doesn't.)

may not be necessary.  It doesn't really advance our argument and could be viewed as a slam on other countries. Consider removing?

**Comment by MatthewHeun** [comment]
Limitation: GDP is self-reported.

**Comment by jgvanantwerp** [comment]
Because GDP data are self-reported at the national level but are aggregated 
internationally, there can be issues of reliability and transparency, 
in addition to the other caveats about what GDP measures and what it doesn't.
