### ISSUE TITLE
Ch4 extraneous sentence?

### ISSUE THREAD

**Issue by MatthewHeun** [MatthewHeun/MCBook2021#343]
In Ch4, we have this sentence:

Indeed, growth in GDP per capita~\Aparen{} is the explicit goal of many economic policies.

That sentence seems extraneous to the point at hand. Consider removing?

**Comment by jgvanantwerp** [comment]
in context:
1. Although production and consumption are in balance, both may change together.
2. Indeed, growth in GDP per capita~\Aparen{} is the explicit goal of many economic policies.
3. There are two ways the economy can increase GDP.

sentence 1 refers back to the previous section.  sentence 2 makes the point that often we *try* to change (usually increase) consumption. sentence 3 states there are different strategies for change. 

I thought it flowed. Does this explanation help?

**Comment by MatthewHeun** [comment]
That's helpful to know how you connect the dots. I would think we could be more explicit about connecting the dots. I propose this revision:

Growth in GDP per capita~\Aparen{} is the explicit goal of many economic policies.
There are two ways the economy can increase GDP, 
either
(a)~by consuming \emph{more} inputs 
or
(b)~by using existing inputs more \emph{efficiently} (meaning that \mft{R} goes down).
Economic inputs include labor, capital, energy, and materials.
In the long run, growing output by scaling up the inputs does not increase 
affluence~\Aparen{} because more workers are needed to gather, process, and use the 
additional resources.
That leaves efficiency as the primary means of boosting affluence.
From a sustainability point of view, we should want everything to be used
as efficiently as possible; inefficiency of any kind is not desirable.

However, growth in GDP has implications for sustainability.
GDP is quantified by consumption.
But because consumption and production are in balance, 
rising economic growth means that production
is an outcome of many economic policies.
Growth in production also means growth in resource extraction and waste emissions.
So policies that encourage economic growth 
often have negative implications for environmental sustainability.


Both the original and the proposed revision are in the LaTeX for Ch4. JVA to consider and make a final decision.

**Comment by jgvanantwerp** [comment]
accepted.
