### ISSUE TITLE
Section 4.2: Economic growth and recession

### ISSUE THREAD

**Issue by MatthewHeun** [MatthewHeun/MCBook2021#344]
In Section 4.2, we talk about efficiency and productivity. Are those words synonyms? If so, should we say so? If not, should we define each?

**Comment by jgvanantwerp** [comment]
After considering it, i think not. We've got efficiency in the preface table. The way we're using the words in section 4.2 is their straightforward, everyday definitions. I'm pretty sure I don't want to restrict myself to a strict economist's definitions. And, we're not trying to be an economics book.

**Comment by MatthewHeun** [comment]
Should we put "productivity" in the preface table?
