### ISSUE TITLE
End-of-sentence footnote markers before or after the period?

### ISSUE THREAD

**Issue by MatthewHeun** [MatthewHeun/MCBook2021#347]
Do we like this:

<img width="779" alt="image" src="https://user-images.githubusercontent.com/3308246/149630740-06d0974a-19da-439e-866c-ecad066b5f9f.png">

Or would we rather have this:

<img width="746" alt="image" src="https://user-images.githubusercontent.com/3308246/149630809-7bde7327-1c0a-440f-b92c-8ef4d07c159c.png">

I like "after," because the footnote is applying to the whole sentence, not to the last word in the sentence. 

JVA should make a decision.

**Comment by jgvanantwerp** [comment]
Chicago manual of style (the other CSM) also goes with "after," so after it is.
See: https://www.chicagomanualofstyle.org/qanda/data/faq/topics/Punctuation/faq0020.html
Please see CMOS 14.26: “A note number should generally be placed at the end of a sentence or at the end of a clause. The number normally follows a quotation (whether it is run into the text or set as an extract). Relative to other punctuation, the number follows any punctuation mark except for the dash, which it precedes.”
for examples: https://morlingcollege.libguides.com/c.php?g=392518&p=2666526
