### ISSUE TITLE
Ch2 improvement: add warming vs. emissions graph

### ISSUE THREAD

**Issue by MatthewHeun** [MatthewHeun/MCBook2021#348]
The IPCC report has this graph:

<img width="695" alt="image" src="https://user-images.githubusercontent.com/3308246/149636245-f2d8c15c-400b-4e3d-bab0-2640c0a20046.png">

If we could get Anjana to extract the data from the graph, I think it would be good to include this in Ch2, alongside the CO2 emissions graph. It would be easy to make.

What does JVA think?

**Comment by jgvanantwerp** [comment]
sure!

**Comment by MatthewHeun** [comment]
OK. Searching for the data now.

**Comment by MatthewHeun** [comment]
All the data appear to be at

http://data.ceda.ac.uk/badc/ar6_wg1/data/spm/spm_10/v20210809

**Comment by MatthewHeun** [comment]
Oh yeah! Look at this:

<img width="770" alt="image" src="https://user-images.githubusercontent.com/3308246/149637922-0e7c7214-17b5-46af-84b5-ec857e451e35.png">

1990 shows where we were in that year, with 1500 GtCO2 budget. 1.5 °C shows that we have 500 GtCO2 budget remaining. The red lines are various IPCC scenarios that I will describe in the caption.

I think this will seal the deal on the climate discussion in Ch2!

**Comment by MatthewHeun** [comment]
At present, it looks like this:

<img width="706" alt="image" src="https://user-images.githubusercontent.com/3308246/149638808-0cbaed6a-b39f-4f10-bb7d-ecb07f6f6c59.png">

I need to do a better job of formatting the caption.

**Comment by MatthewHeun** [comment]
OK. Here is the "final" version for today.

<img width="683" alt="image" src="https://user-images.githubusercontent.com/3308246/149639083-9b7f7335-e66b-486d-85e0-1226938b2106.png">

I think this is a very serious graph, because it shows the predicament we are facing. I'm glad we put it in the book.

**Comment by MatthewHeun** [comment]
Looking back at the IPCC graph, it looks like "Today" is actually 2019. I need to change the text and graph to reflect that reality.

**Comment by jgvanantwerp** [comment]
2011 is a typo (in SSP1-2.6)

**Comment by MatthewHeun** [comment]
Fixed. Actually fixed when I moved the scenario descriptions to a table.
