### ISSUE TITLE
Figure 2.5 I -> I_CO2

### ISSUE THREAD

**Issue by jgvanantwerp** [MatthewHeun/MCBook2021#349]
Search and replace $I$, \mft{I}, and \Iparen. 
Don't use I when we mean I_CO2. 

Relatedly, R is not resources and shouldn't be used as a synonym for resources.
(Resources would be P*A*R).

**Comment by MatthewHeun** [comment]
Fixed caption for Figure 2.5. 

Searched for $I$ and found no other places where we should be using I_CO2.

But really should search for \Iparen{}.
