### ISSUE TITLE
Figure 2.6 caption

### ISSUE THREAD

**Issue by jgvanantwerp** [MatthewHeun/MCBook2021#351]
1. In the caption of figure 2.6,  all of the Cs are missing the degree symbol. For example, "1.5 C."
2. Also, the 2s in all the CO2s are not subscripted. 
3. There isn't a "Source:" (not necessarily a problem, but inconsistent with other figures.)

4. Lastly, the sentence "SSP2-4.5 assumes CO2 emissions stay at current levels until 2050, then falling but not reaching net zero by 2100 to yield 2.7 C warming by 2100" is rather convoluted. 

How about: "SSP2-4.5 assumes CO2 emissions stay at current levels until 2050 and then fall, but not reach net zero by 2100, to yield 2.7 C warming by 2100."

**Comment by MatthewHeun** [comment]
Later versions of the figure caption already addressed items 1-3 🙂. 

The very LONG caption has been split. There is now a table containing the scenarios to which the figure caption refers. I made the suggested edit (4) to the table.
