### ISSUE TITLE
micro plastics as an affluence externality

### ISSUE THREAD

**Issue by jgvanantwerp** [MatthewHeun/MCBook2021#353]
Discussion question to address the source of micro plastics and range of options for dealing with the problem.

**Comment by MatthewHeun** [comment]
I added this question:

>       Economist Robert Gordon argues that GDP vastly underestimates 
>       the benefits to humanity of innovation and new technologies.
>       One example could be innovations in clothing over recent decades.
>       Although the design of clothing (shirts, blouses, trousers, pants)
>       remains mostly unchanged since the 1960s, 
>       we now benefit from enhanced comfort due to improved fabrics.
>       And yet, these new fabrics produce plastics pollution in the form of microfibers
>       that enter waterways, lakes, oceans, and soil.
>       So the new fabrics make our lives better with the negative externality
>       of microfiber pollution.
>       What can be done to address these environmental impacts?
>       What resources (monetary and otherwise) 
>       would be required to reduce microfiber pollution?

JVA to review and edit.

**Comment by jgvanantwerp** [comment]
I'd add to the end: "How do you view the tradeoff of having inexpensive, comfortable clothes versus having microplastic pollution? On the balance, has the innovation of synthetic fibers been a good thing or not good thing? What actions could be taken to shift the balance towards more sustainability?"
