### ISSUE TITLE
Figure 3.4 needs (a), (b), and (c) subfigure labels

### ISSUE THREAD

**Issue by jgvanantwerp** [MatthewHeun/MCBook2021#354]
related to #337.

I want to use \label{fig:dtt_crude_rates} for the top, \label{fig:dtt_population} for the middle, and \label{fig:dtt_pop_pyramid} for the bottom.

If I reference the subfigure directly, I expect it will give the subfigure name in its entirety. For instance. Figure~\ref{fig:dtt_crude_rates} --> "Figure 3.4a" right? (that is, it doesn't just give "a".)

However, my attempt to implement this just produced Figure ??

Can MKH help?

(We should also look at a similar change for Figure 2.3., at least. Maybe others.)

**Comment by MatthewHeun** [comment]
For Figure 2.3, you can already do Figure~\ref{fig:GA4} to get 

<img width="151" alt="image" src="https://user-images.githubusercontent.com/3308246/149693510-3aafa6cf-a14f-4301-bea5-6c58d1122faa.png">

For Figure 3.4, I would need to add labels and captions for each subfigure, if desired. Is it desired?

**Comment by jgvanantwerp** [comment]
Ah. I inserted labels but I'm missing the subcaption. I'll do pattern matching off Figure 2.3 to make it work.

**Comment by MatthewHeun** [comment]
OK. We need to watch the vertical extent of the figure. With subfigure labels, the entire figure might be longer than the piece of paper (less top and bottom margins). We may need to split into separate figures.

**Comment by jgvanantwerp** [comment]
It fits, even with the three subfigure labels.

**Comment by MatthewHeun** [comment]
Should we add Stage labels to all subfigures?

**Comment by jgvanantwerp** [comment]
Yes, probably.
It won't add height to the top one but it might to the bottom.

**Comment by MatthewHeun** [comment]
OK. I'll assign to me to add the Stage labels.

**Comment by MatthewHeun** [comment]
Added the stage labels and am now closing.
