### ISSUE TITLE
clarify sentence?

### ISSUE THREAD

**Issue by jgvanantwerp** [MatthewHeun/MCBook2021#355]
The last sentence of the second paragraph of section 4.1 is 
"In this example, transport is known as an ``energy service,'' the purpose of travel."
(It's at the bottom of the first page of chapter 4---page 55.)

The sentence is unclear. 
(In part, I think, because "transport" as a noun is more a British expression than an American one
https://grammar.collinsdictionary.com/us/english-usage/what-is-the-difference-between-transport-and-transportation)

Options:
1. "In this example, transportation is an ``energy service.'' The purpose is travel."
2. "In this example, the purpose is to travel. Transportation is the ``energy service'' that makes travel possible." 
3. ""In this example, the purpose is to travel. Transportation is the ``energy service, that is, the means that makes travel possible."
4.  Cut the sentence. It's only purpose is to define "energy service."

**Comment by MatthewHeun** [comment]
Interesting! I might have several Britishisms sneaking into my diction, working with many of them on various scholarship activities. 

I liked that paragraph, but it must not be clear enough.

From:

> For instance, when travelling from point A to point B, 
> most travelers don't care whether their car runs on electricity or gasoline.
> The energy consumption is only the means to the end.
> In this example, transport is known as an ``energy service,''
> the purpose of travel.

To:

> For instance, when travelling from point A to point B, 
> most travelers don't care whether their car runs on electricity or gasoline.
> The purpose of the energy consumption is transportation.
> The energy consumption is only a means to that end.
> Transportation (the purpose) is an example of an ``energy service.''
