### ISSUE TITLE
Add information about units to preface table

### ISSUE THREAD

**Issue by MatthewHeun** [MatthewHeun/MCBook2021#356]
To make things clear for the reader, I suggest the following changes to the preface table:

From:

> Efficacy              & The ratio $\frac{\text{energy service}}{\text{energy input}}$. \\
> Efficiency            & The ratio $\frac{\text{output}}{\text{input}}$, often for energy.  \\
> \multirow{2}{*}{Intensity}  & A ratio of unlike quantities, \\
>                            & for example $\mft{R} = \frac{\text{resource consumption}}{\text{GDP}}$. \\

To:

> Efficacy              & The ratio $\frac{\text{energy service}}{\text{energy input}}$, with different units in numerator and denominator. \\
> Efficiency            & A unitless ratio $\frac{\text{output}}{\text{input}}$, often for energy.  \\
> \multirow{3}{*}{Intensity}  & A ratio of unlike quantities, \\
>                            & for example $\mft{R} = \frac{\text{resource consumption}}{\text{GDP}}$. \\
>                            & with different units in numerator and denominator.

Is that OK with JVA?

A reason it would *not* be OK is that the word ``efficiency'' is used colloquially in Ch4 to mean economic output/resource input, actually an efficacy.

**Comment by jgvanantwerp** [comment]
OK

**Comment by MatthewHeun** [comment]
We may want to include this sentence in Ch4. 

> Innovation can lead to energy efficiency which (barring rebound or backfire) can make the economy more productive and efficacious.

Also, Ch4 needs to be reviewed carefully for uses of the words efficiency, efficacy, productivity, etc.

**Comment by MatthewHeun** [comment]
Units information has been added to the preface table. Next step, review Ch4 for consistency.

**Comment by MatthewHeun** [comment]
Definitions:

* Efficiency is a unitless output/input ratio. (like energy out/energy in to a power plant)
* EROI is a unitless ratio of output/input, but the input is not the feedstock.
* Efficacy is a unit-ed ratio of output/input. (like lumens/watt)
* Intensities are unit-ed ratios of input/output. (like R = resources/ GDP)
* Productivity is economic output/economic input.

So the Impact intensity of resources is not really an intensity. I changed all instances to be "impact of resources (X)".

**Comment by MatthewHeun** [comment]
Edited in lots of areas.
