### ISSUE TITLE
Gas pipeline vs. electricity distribution "efficiency" -- Project

### ISSUE THREAD

**Issue by jgvanantwerp** [MatthewHeun/MCBook2021#359]
Research the efficiency of electricity generation and distribution. Account for line losses as well as the efficiency of power generation from coal or natural gas.
Research the efficiency of natural gas extraction and distribution. Account for the amount of gas leaking from pipes and storage facilities.
Which method of delivering energy to the consumer has the greatest efficiency (energy/energy)? Which has the least emissions (GHG/MJ delivered)? Which is most cost effective? Are there other considerations that should influence the choice of which to buy, such as reliability, energy storage, or suitability for a particular application?

**Comment by jgvanantwerp** [comment]
related to #245

**Comment by jgvanantwerp** [comment]
Probably a link to consider as a different question:
https://www.latimes.com/environment/newsletter/2021-12-23/is-tejon-ranch-development-good-for-climate-boiling-point

Also, are you familiar with the Allum power cycle? https://www.youtube.com/watch?v=1zDZmIDbDO0

**Comment by MatthewHeun** [comment]
Added as the last project in Ch5.

JVA to review.

**Comment by jgvanantwerp** [comment]
done.
