### ISSUE TITLE
Section 11.2.1 seems out of place or needs to be refocused

### ISSUE THREAD

**Issue by MatthewHeun** [MatthewHeun/MCBook2021#361]
In Chapter 11 (collective action), Section 11.2.1 is titled "Choices," and all its examples are for individuals.

It seems that this section should be focused on collectives, not individuals.

Or maybe it should be moved closer to the top of the chapter?

**Comment by jgvanantwerp** [comment]
Section 11.2 is about the actions, not about collectives. Individual choices are probably easier to understand. We could add some collective choices. Government buying EVs for workers that drive. A company that buys renewable energy for its operations. A university that goes net zero. A hospital that does a deep energy retrofit on its property.

**Comment by MatthewHeun** [comment]
Yes, but I think it may be confusing to readers that individual actions are discussed *after* a section about collectives (11.1). It feels like the chapter already turned the corner to talking about collectives.

**Comment by MatthewHeun** [comment]
I thought about those options, too. Nothing jumped out at me as the obvious solution. So I made an issue! I agree sleeping on it and discussing in the morning.

**Comment by jgvanantwerp** [comment]
Government could appoint an "extreme heat official" like Miami, Athens, and Freetown.

**Comment by jgvanantwerp** [comment]
we revised 11.1 and 11.2
