### ISSUE TITLE
Crop percentages by what? Mass? Calories? Land area?

### ISSUE THREAD

**Issue by MatthewHeun** [MatthewHeun/MCBook2021#365]
In Ch10, we have this:

> The four largest crops in the U.S. are wheat (32\% of total crops), corn (30\%),
> soybeans (20\%), and cotton (10\%). 

Is this by mass, land area, calories?  Probably best to say.

Further, we say

> In contrast, the area where we live and work
> is a relatively small 70 million acres (3\%).

Is this by calories? By area?

**Comment by jgvanantwerp** [comment]
The area where we live and work is in acres. it's an area.

**Comment by MatthewHeun** [comment]
OK on the area where we live and work.

But what about

> The four largest crops in the U.S. are wheat (32\% of total crops), corn (30\%),
> soybeans (20\%), and cotton (10\%). 
> All other crops combined account for only 8\% of total crops.

Are those percentages by area, too? Or by calories?

**Comment by jgvanantwerp** [comment]
FAO data for 2020 suggest that those percentages are of acres that are cultivated.
However, I'm getting 34%, 34%, 15%, and 3.6% for maize, soybeans, wheat, and seed cotton using the 2020 FAO data. 
By mass, corn is over 50%.
(Since we don't eat cotton, the 10% isn't calories.)

**Comment by MatthewHeun** [comment]
The sentence now says:

> The four largest crops in the U.S.\ by cultivated area are
> maize~(34\%),
> soybeans~(34\%), 
> wheat~(15\%), and 
> seed cotton~(3.6\%).
> All other crops combined account for less than 14\% of cultivated area.
> In contrast, the area where we live and work
> is a relatively small 70 million acres (3\% of total land area).
> The U.S. is relatively sparsely populated.

It would be good to add a reference to this claim.

**Comment by jgvanantwerp** [comment]
FAO Global Statistical Yearbook, FAO Regional Statistical Yearbooks.
http://www.fao.org/faostat/en/#data/QC
2020

**Comment by MatthewHeun** [comment]
I'll add the reference.

**Comment by MatthewHeun** [comment]
When I open that link, I see a blank page. Is that the expected behavior?

<img width="1211" alt="image" src="https://user-images.githubusercontent.com/3308246/150260927-c7a9950e-62de-483b-b957-569b0df378ce.png">

**Comment by jgvanantwerp** [comment]
![image](https://user-images.githubusercontent.com/48030444/150261502-f266c50d-8abe-46bc-b51c-1ad83273ef8f.png)

**Comment by jgvanantwerp** [comment]
I think the FAO has a typo in their metadata page. The correct URL should end in an L.
https://www.fao.org/faostat/en/#data/QCL

**Comment by MatthewHeun** [comment]
Added the correct reference. Now closing.
