### ISSUE TITLE
Which band in Figure 10.1?

### ISSUE THREAD

**Issue by MatthewHeun** [MatthewHeun/MCBook2021#366]
We have:

> Figure~\ref{fig:USlanduse} shows that growing timber is a major use of U.S.\ land.

But I don't see that from Figure 10.1. Which band represents the timber growing? It would clarify to say which one.

My guess is "Forest (grazed)" or "Forest (not grazed)". Both?

**Comment by jgvanantwerp** [comment]
I think it's both. Forest (grazed_) is small.

**Comment by MatthewHeun** [comment]
OK. I'll add a note to that effect.

**Comment by MatthewHeun** [comment]
The sentence now reads:

> Figure~\ref{fig:USlanduse} shows that growing timber 
> (both grazed and not-grazed forest)
> is a major use of land in the U.S.

Closing.
