### ISSUE TITLE
Deforestation leads to GHG emissions?

### ISSUE THREAD

**Issue by MatthewHeun** [MatthewHeun/MCBook2021#367]
In Ch10, we have

> Second, the net effect is deforestation, which results in greenhouse gas emissions.

Deforestation results is LESS GHG sequestration, not emissions directly. 

(Unless we mean the CO2 emissions from diesel consumption in machines that do the deforestation.

**Comment by jgvanantwerp** [comment]
![image](https://user-images.githubusercontent.com/48030444/150248118-4e7c9cf8-814a-4890-a317-d73ddad2ec25.png)

From the IPCC SPM "Expansion of areas under agriculture and forestry, ... these changes have contributed
to increasing net GHG emissions (very high confidence),"

**Comment by jgvanantwerp** [comment]
Maybe add the word "net" and call it a day?

**Comment by jgvanantwerp** [comment]
added "net" and a citation to IPCC SPM.
