### ISSUE TITLE
Section 10.2.2 needs to end with a sustainability challenge question

### ISSUE THREAD

**Issue by MatthewHeun** [MatthewHeun/MCBook2021#368]
Other sections end with a question. But this one does not. Maybe others?

**Comment by MatthewHeun** [comment]
Also section 10.2.3 needs to end with a question.

**Comment by jgvanantwerp** [comment]
A sustainability challenge associated with land use and transportation is "how do we arrange the different elements of the transportation system to move goods and people quickly with little environmental impact?"
A sustainability challenge associated with land use and agriculture is "how can we retain the most fertile cropland as cropland?"
