### ISSUE TITLE
Efficiency or efficacy?

### ISSUE THREAD

**Issue by MatthewHeun** [MatthewHeun/MCBook2021#370]
In section 10.3, we have 

> The question of allocation therefore becomes a question of land use efficiency. 

And we have Section 10.3.1 titled "Land use efficiency." 

Does this use of the word "efficiency" align with the definition of the word in the preface table?

> Efficiency            & A unitless ratio $\frac{\text{useful output}}{\text{input}}$, often for energy. \vspace{1mm} \\

Probably best to clarify.

**Comment by jgvanantwerp** [comment]
clarified. now it says "efficacy." MHK to give section 10.3 a read through to confirm.
