### ISSUE TITLE
Productivity in sparing/sharing green box

### ISSUE THREAD

**Issue by MatthewHeun** [MatthewHeun/MCBook2021#372]
In the sparing/sharing green box, we have

> Land ``sparing'' seeks to minimize the amount of agricultural land needed for humans
> but maximizing the productivity of that land, even if it means input-intensive farming
> that results in less biodiversity \emph{on the farm}. 

In the preface table, we have

> \multirow{3}{*}{Productivity} & The ratio $\frac{\text{economic output}}{\text{production input}}$, a type of efficacy, \\
>                               & with different units in numerator~(\$) and denominator \\
>                               & (for example, capital, labor, energy, or materials). \vspace{1mm} \\

Are we meaning productivity in that economic sense here?

If so, no changes needed. If not, best to pick a different word.

**Comment by MatthewHeun** [comment]
The same word (productivity) appears in Section 10.4. Double-check the meaning there, too.

**Comment by jgvanantwerp** [comment]
i think it's good.  Yes, we do mean productivity in an economic sense.
