### ISSUE TITLE
Items to raise with M&C

### ISSUE THREAD

**Issue by MatthewHeun** [MatthewHeun/MCBook2021#374]
Here are some LaTeX-related issues to raise with M&C at the time of submission.

~~* We would like all of question and project references to appear as hyperlinks. At present, only the question number of project number are hyperlinks. For example, in "Q1.2", only the "2" is hyperlinked.~~
* We would like a reference list for each chapter at the end of each chapter.
* Question and Project numbers bleed into the blue vertical line on verso leaves when the number is more than x.y. For example, Q12.10.
* Index has \leftmark and \rightmark of "12. Index". It should be "Index" (without chapter number).
* Table 0.1 should be labeled "Table Preface.1" or something better.

Here are some other issues:

* Figure 11.2(a) is from Google Maps. The license says we can use the image for publications of up to 5000 copies. (See Issue #143.) Is that OK?

**Comment by MatthewHeun** [comment]
I figured out how to get full Q1.1 and P1.1 references with \ref{question:X} and \ref{project:Y}. So no need to ask M&C about that.

**Comment by jgvanantwerp** [comment]
There's a reference to IEEE Xplore in the Preface. Should that stay or change?

**Comment by jgvanantwerp** [comment]
Ask M&C to do an "about the cover" blurb inside the cover.

**Comment by jgvanantwerp** [comment]
Alphabetization of "mineral-resources depletion"

**Comment by MatthewHeun** [comment]
All of these items have been fixed or moved to other issues. Thus, I'm closing this issue now.
