### ISSUE TITLE
Aral Sea before-after?

### ISSUE THREAD

**Issue by MatthewHeun** [MatthewHeun/MCBook2021#379]
Yes! Aral Sea before-after is a great idea in Section 9.2.1. Unfortunately, the link that JVA provided:

https://www.carecinstitute.org/events/international-symposium-on-ecological-restoration-and-management-of-the-aral-sea/

does not have a clearly defined license for the photo. If we find an image we can use, I'll be happy to add to the book.

**Comment by jgvanantwerp** [comment]
Here's the Wiki commons link: https://commons.wikimedia.org/wiki/Category:Aral_Sea
Also, from that page, see the link to the satellite image pages. I'll search NASA to see if they have something we can use.

**Comment by jgvanantwerp** [comment]
https://earthobservatory.nasa.gov/world-of-change/AralSea
https://earthobservatory.nasa.gov/images/146487/a-dusty-day-over-the-aral-sea

**Comment by MatthewHeun** [comment]
Figure 9.1 now shows before and after (2000 and 2018) satellite photos of the Aral Sea.
