### ISSUE TITLE
``extraction''

### ISSUE THREAD

**Issue by jgvanantwerp** [MatthewHeun/MCBook2021#387]
At the end of the first paragraph in section 5.1 the word extraction appears in double quotes.
I'm going to suggest that it be bolded and indexed as just extraction (not extraction of biomass, extraction of ... or whatever).

**Comment by jgvanantwerp** [comment]
Additionally, the term Critical Raw Material appears on page 73 (capitalized, in reference to Table 5.1).
The first index of it appears on page 78, where it is bolded. 
I'm going to suggest/request that the occurrence on p. 73 be bolded, indexed, and not capitalized. The entry on p. 78 then wouldn't be bolded.

**Comment by MatthewHeun** [comment]
Took care of bolding CRM and putting in index. That instance was indexed as materials!critical!raw. Ugh!

**Comment by MatthewHeun** [comment]
Took care of the ``extraction'' request. The index now looks like this:

<img width="330" alt="image" src="https://user-images.githubusercontent.com/3308246/152450113-c1b05e9a-9401-40f3-84ef-c40fe631fcdf.png">

JVA to verify this approach satisfies the request and close.

**Comment by jgvanantwerp** [comment]
looks great
