### ISSUE TITLE
Confusing sentence, section 9.2

### ISSUE THREAD

**Issue by MatthewHeun** [MatthewHeun/MCBook2021#388]
This sentence in the first paragraph of Section 9.2 is confusing. Or at least the "three accountings" don't make sense to me.

<img width="639" alt="image" src="https://user-images.githubusercontent.com/3308246/152454857-1fa8afee-d801-48a7-a44e-13e285d6b8c9.png">

Perhaps JVA can clarify?

**Comment by jgvanantwerp** [comment]
We had a version worked out this morning and I didn't write it down. How about
"Each of way off accounting for inputs and outputs
gives a different nuance to the sustainability impacts
of vehicle manufacturing, use, and disposal."

**Comment by MatthewHeun** [comment]
I think this is pretty close to what we discussed.
