### ISSUE TITLE
"see" format

### ISSUE THREAD

**Issue by MatthewHeun** [MatthewHeun/MCBook2021#392]
I thought we decided on the semicolon "see" format. The last sentence in this paragraph:

<img width="676" alt="image" src="https://user-images.githubusercontent.com/3308246/152462929-d304316f-2440-472c-8182-71bdb0f8ec62.png">

doesn't follow that format. I would have expected to find "; see Figure 9.5.

**Comment by jgvanantwerp** [comment]
this might be a remnant from an earlier revision. Or, I may have deviated from the agreed-upon format because of the citation.
Which would you go with: "...greenhouse-gas emissions [51]; see Figure 9.5." or "...greenhouse-gas emissions; see Figure 9.5 [51]"?
I'm thinking the first one.

**Comment by MatthewHeun** [comment]
I agree. First one.
