### ISSUE TITLE
Eliminate colons?

### ISSUE THREAD

**Issue by MatthewHeun** [MatthewHeun/MCBook2021#393]
In Ch10, the "See Also" items still have colons:

<img width="663" alt="image" src="https://user-images.githubusercontent.com/3308246/152464105-dbad0dcf-cd5e-4bde-9b21-9cf25e522982.png">

I thought we planned to remove the colons. This issue should probably be checked across all chapters.

**Comment by jgvanantwerp** [comment]
I finished a read through last night. I'm up through chapter 6 implementing changes. haven't gotten to 10 yet.
