### ISSUE TITLE
Ch10 paragraph naming

### ISSUE THREAD

**Issue by MatthewHeun** [MatthewHeun/MCBook2021#394]
Section 10.1.2 is called "Affluence". The paragraph immediately under the heading seems to signal that the affluence section will consider resources and wastes. 

<img width="432" alt="image" src="https://user-images.githubusercontent.com/3308246/152649478-009a6c56-a289-4888-b6a6-8d5c8fbb3e42.png">

Indeed, the first paragraph is "Resources". But the second paragraph is "Ecosystem services". I would have expected a title like "Wastes" or "Absorption of wastes by the ecosystem". 

Waste absorption is AN ecosystem service. But there are many ecosystem services. I wonder if the heading should be changed.

JVA to consider the point above, make any changes he deems helpful, and close this issue.

**Comment by jgvanantwerp** [comment]
Waste disposal (ecosystem service)

**Comment by MatthewHeun** [comment]
I'll raise you to 

"Waste disposal (an ecosystem service)"
