### ISSUE TITLE
Move Ch10 paragraph forward?

### ISSUE THREAD

**Issue by MatthewHeun** [MatthewHeun/MCBook2021#395]
This paragraph:

<img width="441" alt="image" src="https://user-images.githubusercontent.com/3308246/152649832-5acf25bc-acd6-461a-a311-9957ed762ae3.png">

might go better at the TOP of Section 10.1.2, rather than at the bottom of the ecosystem services (waste) paragraph. 

JVA to consider, make any desired changes, and close this issue.

**Comment by jgvanantwerp** [comment]
in 10.1 change "the next two sections" to "subsections?"

**Comment by MatthewHeun** [comment]
I would rather suggest this to be the 2nd paragraph of the chapter:

> The sections of this chapter deal with three major sustainability questions related to land use: How do we use land? How does our use of land affect sustainability? How can we transition to more sustainable ways of using land?

Then, how about leading into the next paragraph like this:

> Within those sections, we examine two aspects of land use. The first aspect is the layout or arrangement of different uses of land. Which is more sustainable: to group all the farms, forests, and cities so that each is as large as possible? Or, is it better to intersperse many small farms, forests, and towns? Whereas Chapter 7 was concerned with the sustainability of individual housing units, this chapter considers dwellings and businesses collectively. We consider the sustainability implications of spacing, density, and how transportation links between locations are affected by layout.

> The second aspect of land use is allocation, that is, how much land is used for each purpose? Land can be used for agriculture, recreation, urban or suburban dwellings, or not allocated for direct human use, that is, left as wilderness. Land is the source, directly or indirectly, for all our resources, the sink for much of our waste, and where we ourselves live. We need land to simultaneously satisfy many different wants and needs, including supplying resources, accepting wastes, and providing ecosystem services.

The suggestion is to LEAD with the major structure of the chapter (demand, challenges, transitions). Then talk about what we'll be discussing within the outer structure. I think the suggested order provides better signposting for readers.
