### ISSUE TITLE
Add JVA index items

### ISSUE THREAD

**Issue by MatthewHeun** [MatthewHeun/MCBook2021#396]

**Comment by MatthewHeun** [comment]
Unresolved issue:

* JVA requested that "Not Just Bikes" be indexed to Q8.9. However, Q8.9 does not refer to Not Just Bikes. Solutions: (a) do nothing, (b) add a reference to "Not Just Bikes" in Q8.9 and index.

**Comment by MatthewHeun** [comment]
Unresolved issue:

"Term" appears in JVA's list of terms to be indexed. MKH is not sure what "Term" means. Is that a column title that was inadvertently alphabetized?

**Comment by MatthewHeun** [comment]
At this point, I am done implementing JVA index requests. Only 2 unresolved issues remain (above). I'm assigning to JVA for responses.

**Comment by jgvanantwerp** [comment]
Term was indeed the column heading that was inadvertently sorted into the list. ignore.

**Comment by jgvanantwerp** [comment]
The Not Just Bikes reference is in the caption of Figure 12.2. That figure *is* referenced in Q8.9. Thus, Q8.9 does reference Not Just Bikes, albeit indirectly. I think my preference would be to add it to the index. However, I'm willing to defer on this one.

**Comment by MatthewHeun** [comment]
Not Just Bikes *is* in the index, covering all places where the term appears. It doesn't seem right to index every "once removed" reference to a term in the book. The index would become *massive*. So I strongly prefer to *not* add index "Not Just Bikes" in Q8.9 *unless* we add the term "Not Just Bikes" to Q8.9.

I'm closing this issue now. JVA can reopen if further discussions are desired.
