### ISSUE TITLE
more index issues

### ISSUE THREAD

**Issue by jgvanantwerp** [MatthewHeun/MCBook2021#399]
1. I noticed Larry Niven in the index but not lots of other people, in particular, not Pope JP II.  I suggest removing LN from the index.
2. Mayo Clinic is indexed as "the Mayo Clinic" that is, under T instead of M.
3. thorium is indexed twice, once with its chemical symbol and once without.
4. Let's add Vlog brothers to the index (the chapter 12 See Also).

**Comment by MatthewHeun** [comment]
I *meant* to add John Paul II. And Larry Niven. I would vote for adding them. What does JVA think?

I'll fix items 2-4.

**Comment by MatthewHeun** [comment]
Niven is already in the index:

<img width="318" alt="image" src="https://user-images.githubusercontent.com/3308246/152847645-16c88336-f35f-41a4-adb2-0f0a53c2c43e.png">

I added John Paul II to the index.

Fixed thorium.

Fixed Mayo clinic.

Checked that all beg-of-chapter quotes are in the index.
