### ISSUE TITLE
Add content to chapter 5

### ISSUE THREAD

**Issue by jgvanantwerp** [MatthewHeun/MCBook2021#40]
Define renewable and recyclable resources. Tie into defns of strong and weak sustainability.
Give examples of capacity factors (e.g., timber per time).
Recyclable energy and material efficiencies. 
Some energy per resource examples.
An example of replacing a nonrenewable resource with a renewable resource (Herman Daly's defintion).

**Comment by MatthewHeun** [comment]
Added a discussion on substitution, hearkening back to Daly's definition.

I added a green box discussion on the fourth law of thermodynamics, material processing, and material degradation.

I'm not sure what is meant by "capacity factors" in relation to timber. Did you mean "rates"?

I don't have nay energy per resource definitions at hand. Do you mean "embodied energy"? If so, I can point to some coefficients.

**Comment by jgvanantwerp** [comment]
I think I meant how much timber is available. What is our maximum sustained yield. Applying strong sustainability criterion to figure 5.1
