### ISSUE TITLE
Preface references empty

### ISSUE THREAD

**Issue by MatthewHeun** [MatthewHeun/MCBook2021#408]
When running the chapter bibliography code in the `chap_bibs` branch, the references in the preface come up empty.

<img width="803" alt="image" src="https://user-images.githubusercontent.com/3308246/154185101-4341bf13-cd70-4b44-a467-81b68f910937.png">

<img width="816" alt="image" src="https://user-images.githubusercontent.com/3308246/154185071-cc0591f8-99f3-434d-879a-ca0a7b42104e.png">

**Comment by jgvanantwerp** [comment]
the references in About the Authors are showing up as [?] with no corresponding reference section.

**Comment by MatthewHeun** [comment]
Moved "About the Authors" issue to #410.

**Comment by MatthewHeun** [comment]
I fixed this by hacking the system. The preface and Acknowledgements are now in \mainmatter. Page numbering is forced to roman. Page numbering is set manually.

This approach is a hack around the fact that \include works only in \mainmatter, not in \frontmatter. 

We need to be careful about page numbering for the preface and the acknowledgements. But this will not be a problem unless we add another page to the front matter.

I'm closing this issue for now.
