### ISSUE TITLE
Many references have BOTH doi and URL. Probably should have 1.

### ISSUE THREAD

**Issue by MatthewHeun** [MatthewHeun/MCBook2021#411]
We have a LOT of work to do on the references. Ugh!

**Comment by jgvanantwerp** [comment]
I've been thinking of the doi and url as separate (and complementary) pieces of information.
Let's talk about a strategy for addressing this.

**Comment by jgvanantwerp** [comment]
https://apastyle.apa.org/style-grammar-guidelines/references/dois-urls#:~:text=A%20DOI%20is%20a%20unique,its%20location%20on%20the%20internet.&text=A%20URL%20specifies%20the%20location,bar%20of%20your%20internet%20browser.

**Comment by MatthewHeun** [comment]
This looks to be fixed everywhere!
