### ISSUE TITLE
Suggestion: Add before/after photo of Notre-Dame to Ch1 questions

### ISSUE THREAD

**Issue by MatthewHeun** [MatthewHeun/MCBook2021#48]

**Comment by jgvanantwerp** [comment]
we'd need photos that we have permission to use.

**Comment by jgvanantwerp** [comment]
Search Creative Commons or Wikimedia for images?

**Comment by jgvanantwerp** [comment]
added photos.

**Comment by MatthewHeun** [comment]
The photos are now in the book, above the Questions for Ch1.

<img width="778" alt="image" src="https://user-images.githubusercontent.com/3308246/148003710-c7055294-71b6-441f-9d2c-6abfd21385ec.png">

Closing this issue.
