### ISSUE TITLE
Figure 2.3 (Limits)

### ISSUE THREAD

**Issue by jgvanantwerp** [MatthewHeun/MCBook2021#52]
In subfigure D, I think we want to flip the functions. The limit should crash (tipping point) and the variable decrease with a non-infinite slope.

**Comment by MatthewHeun** [comment]
I'm not sure I agree with this change, but I made it. JVA can decide if that's how he likes it 🙂.

**Comment by jgvanantwerp** [comment]
Yes, this looks bad. Now I’m not sure which comment you’re referring to. I created this issue, then went back and looked at the figure, changed my mind, and edited the issue. I’m wondering if you’re responding to the original issue or the edited version.
