### ISSUE TITLE
Chapter 2: Fix Carbon cycle Sankey diagram

### ISSUE THREAD

**Issue by MatthewHeun** [MatthewHeun/MCBook2021#7]
* Make readable.
* Make fit on page (by changing width).
* Re-create: generate from numbers in a spreadsheet.
* Update to more-recent source of data.

* Also, may need to be moved.

**Comment by jgvanantwerp** [comment]
Moved and scaled. Temporary fix.

**Comment by jgvanantwerp** [comment]
The figure has been deleted. The question is whether anthropomorphic net emissions are to be compared to natural processes.

**Comment by jgvanantwerp** [comment]
could be a project or discussion question. 
Footnote? that points to project.
Ignore?
Not going add several sections of content.
Not going to add figure.
Is the best option to remove humans from the planet? What is the role of humans in the natural world?

**Comment by jgvanantwerp** [comment]
Now a footnote.

**Comment by jgvanantwerp** [comment]
Added Questions 2.17 and 2.18 and Project 2.7.

MKH to review and close the issue.

**Comment by MatthewHeun** [comment]
Made minor edits to JVA's text. Closing now.
