### ISSUE TITLE
change title to "A Framework for Sustainability Thinking"

### ISSUE THREAD

**Issue by jgvanantwerp** [MatthewHeun/MCBook2021#73]
Other versions of this idea are more wordy and so I don't like them as well.
A framework for thinking about sustainability [challenges]

**Comment by MatthewHeun** [comment]
Paul Brockway suggests the following titles:

for the title, I looked at it and then the section titles and what you wrote in the abstract:
A Framework for Sustainability Thinking: An Engineering Perspective
·introduction to the many challenges of sustainability
·The first half of the book develops a framework for sustainability thinking.
·The second half considers application areas and personal and corporate responses to sustainability challenges
·PART I IPARC Identity
·PART II Sustainability Challenges.
·PART III Collective and Personal Actions
·The focus of this book is on the many challenges of sustainability

I am not sure its an engineering perspective. 

the IPAT and now the IPARC eqn isn’t engineering per se.

the words that came up frequently as I read were:
·introduction
·challenges
·sustainability
·student

so maybe

·“A student introduction to sustainability challenges”

but even then its missing a sense of geographic scaleso maybe

·“A student introduction to global sustainability challenges”

**Comment by MatthewHeun** [comment]
Changed to 

A Framework for Sustainability Thinking: A student's introduction to global sustainability challenges
