### ISSUE TITLE
Substitution example of injection molded plastic for steel

### ISSUE THREAD

**Issue by jgvanantwerp** [MatthewHeun/MCBook2021#82]
The third-to-last paragraph of section 5.2 gives the example of substituting plastic for steel. But two sentences earlier substitution is defined as "replacing consumption of non-renewable resources by consumption of renewable resources." In the plastic and steel example, both are equally nonrenewable and/or recyclable. Consider either a different example or clarifying the definition.

**Comment by MatthewHeun** [comment]
JVA rewrote. MKH to review.

**Comment by MatthewHeun** [comment]
I reviewed and edited JVA's rewrite. For the time being, I did not change much about strong/weak sustainability, realizing that further edits are coming.
